"""
Module: gshare.color
Dumped: 2025-12-16T22:16:58.303249
Generated by SDK Dumper
"""

# module: gshare.color

# Imports
import MType
import cc
import colorsys
import six2
import webcolors

# Variables
COMPONENT = 'Client'
hx = '#9acd32'
is_client = True
name = 'yellowgreen'

# Classes
class Color:
    aliceblue = <gshare.color.Color object at 0x0000018E8459BA50>
    antiquewhite = <gshare.color.Color object at 0x0000018E845B5690>
    aqua = <gshare.color.Color object at 0x0000018E845B5790>
    aquamarine = <gshare.color.Color object at 0x0000018E845B57D0>
    azure = <gshare.color.Color object at 0x0000018E845B5810>
    beige = <gshare.color.Color object at 0x0000018E845B5850>
    bisque = <gshare.color.Color object at 0x0000018E845B5890>
    black = <gshare.color.Color object at 0x0000018E846A9890>
    blanchedalmond = <gshare.color.Color object at 0x0000018E9F7F2790>
    blue = <gshare.color.Color object at 0x0000018E845B5710>
    blueviolet = <gshare.color.Color object at 0x0000018E8667BD90>
    brown = <gshare.color.Color object at 0x0000018EFF489410>
    burlywood = <gshare.color.Color object at 0x0000018E853887D0>
    cadetblue = <gshare.color.Color object at 0x0000018E845B5910>
    chartreuse = <gshare.color.Color object at 0x0000018E845B5950>
    chocolate = <gshare.color.Color object at 0x0000018EFF431850>
    coral = <gshare.color.Color object at 0x0000018E845B58D0>
    cornflowerblue = <gshare.color.Color object at 0x0000018E845B59D0>
    cornsilk = <gshare.color.Color object at 0x0000018E87A55050>
    crimson = <gshare.color.Color object at 0x0000018E845B5750>
    cyan = <gshare.color.Color object at 0x0000018E845B5A50>
    darkblue = <gshare.color.Color object at 0x0000018E87A54ED0>
    darkcyan = <gshare.color.Color object at 0x0000018E9F644310>
    darkgoldenrod = <gshare.color.Color object at 0x0000018EFF47E110>
    darkgray = <gshare.color.Color object at 0x0000018E845B5A90>
    darkgreen = <gshare.color.Color object at 0x0000018E845B5AD0>
    darkgrey = <gshare.color.Color object at 0x0000018EFF429050>
    darkkhaki = <gshare.color.Color object at 0x0000018E8667BF10>
    darkmagenta = <gshare.color.Color object at 0x0000018E845B5990>
    darkolivegreen = <gshare.color.Color object at 0x0000018E845B5B90>
    darkorange = <gshare.color.Color object at 0x0000018E845B5BD0>
    darkorchid = <gshare.color.Color object at 0x0000018EFF47D910>
    darkred = <gshare.color.Color object at 0x0000018E845B5B10>
    darksalmon = <gshare.color.Color object at 0x0000018E845B5C50>
    darkseagreen = <gshare.color.Color object at 0x0000018E845B5C90>
    darkslateblue = <gshare.color.Color object at 0x0000018EFF489050>
    darkslategray = <gshare.color.Color object at 0x0000018E845B5B50>
    darkslategrey = <gshare.color.Color object at 0x0000018E845B5D10>
    darkturquoise = <gshare.color.Color object at 0x0000018E845B5D50>
    darkviolet = <gshare.color.Color object at 0x0000018E845B5D90>
    deeppink = <gshare.color.Color object at 0x0000018EFF4290D0>
    deepskyblue = <gshare.color.Color object at 0x0000018E845B5C10>
    dimgray = <gshare.color.Color object at 0x0000018E845B5E10>
    dimgrey = <gshare.color.Color object at 0x0000018E845B5E50>
    dodgerblue = <gshare.color.Color object at 0x0000018E845B5E90>
    firebrick = <gshare.color.Color object at 0x0000018E845B5ED0>
    floralwhite = <gshare.color.Color object at 0x0000018E845B5F10>
    forestgreen = <gshare.color.Color object at 0x0000018E845B5F50>
    fuchsia = <gshare.color.Color object at 0x0000018EFF429110>
    gainsboro = <gshare.color.Color object at 0x0000018E845B5CD0>
    ghostwhite = <gshare.color.Color object at 0x0000018E845B5FD0>
    gold = <gshare.color.Color object at 0x0000018E845B6010>
    goldenrod = <gshare.color.Color object at 0x0000018E853ABDD0>
    gray = <gshare.color.Color object at 0x0000018E845B5DD0>
    green = <gshare.color.Color object at 0x0000018E845B60D0>
    greenyellow = <gshare.color.Color object at 0x0000018EFF42A150>
    grey = <gshare.color.Color object at 0x0000018E845B6090>
    honeydew = <gshare.color.Color object at 0x0000018E845B5F90>
    hotpink = <gshare.color.Color object at 0x0000018E845B6150>
    indianred = <gshare.color.Color object at 0x0000018E845B6190>
    indigo = <gshare.color.Color object at 0x0000018E8667BFD0>
    ivory = <gshare.color.Color object at 0x0000018E87A55010>
    khaki = <gshare.color.Color object at 0x0000018E9F7F25D0>
    lavender = <gshare.color.Color object at 0x0000018E846A9AD0>
    lavenderblush = <gshare.color.Color object at 0x0000018EFF47E1D0>
    lawngreen = <gshare.color.Color object at 0x0000018E846A9450>
    lemonchiffon = <gshare.color.Color object at 0x0000018EFF42A190>
    lightblue = <gshare.color.Color object at 0x0000018E84686810>
    lightcoral = <gshare.color.Color object at 0x0000018E8667BF90>
    lightcyan = <gshare.color.Color object at 0x0000018E845B6110>
    lightgoldenrodyellow = <gshare.color.Color object at 0x0000018E9F7F2590>
    lightgray = <gshare.color.Color object at 0x0000018E845B6050>
    lightgreen = <gshare.color.Color object at 0x0000018E845B6290>
    lightgrey = <gshare.color.Color object at 0x0000018E845B6250>
    lightpink = <gshare.color.Color object at 0x0000018E845B62D0>
    lightsalmon = <gshare.color.Color object at 0x0000018E845B6310>
    lightseagreen = <gshare.color.Color object at 0x0000018E8667BF50>
    lightskyblue = <gshare.color.Color object at 0x0000018EFF47CA50>
    lightslategray = <gshare.color.Color object at 0x0000018E9F7F2550>
    lightslategrey = <gshare.color.Color object at 0x0000018E9F7F2710>
    lightsteelblue = <gshare.color.Color object at 0x0000018EFF47E150>
    lightyellow = <gshare.color.Color object at 0x0000018E9F644350>
    lime = <gshare.color.Color object at 0x0000018E845B6350>
    limegreen = <gshare.color.Color object at 0x0000018E845B6390>
    linen = <gshare.color.Color object at 0x0000018EFF47E5D0>
    magenta = <gshare.color.Color object at 0x0000018E9F7F2950>
    maroon = <gshare.color.Color object at 0x0000018EFF489150>
    mediumaquamarine = <gshare.color.Color object at 0x0000018E866900D0>
    mediumblue = <gshare.color.Color object at 0x0000018EFF433A50>
    mediumorchid = <gshare.color.Color object at 0x0000018E9F7F2A50>
    mediumpurple = <gshare.color.Color object at 0x0000018E846A9FD0>
    mediumseagreen = <gshare.color.Color object at 0x0000018EFF432010>
    mediumslateblue = <gshare.color.Color object at 0x0000018EFF429ED0>
    mediumspringgreen = <gshare.color.Color object at 0x0000018EFF433A90>
    mediumturquoise = <gshare.color.Color object at 0x0000018E85333A50>
    mediumvioletred = <gshare.color.Color object at 0x0000018EFF4D7A90>
    midnightblue = <gshare.color.Color object at 0x0000018E845B63D0>
    mintcream = <gshare.color.Color object at 0x0000018E845B61D0>
    mistyrose = <gshare.color.Color object at 0x0000018E845B6450>
    moccasin = <gshare.color.Color object at 0x0000018E845B6490>
    navajowhite = <gshare.color.Color object at 0x0000018E846A9C10>
    navy = <gshare.color.Color object at 0x0000018E845B64D0>
    oldlace = <gshare.color.Color object at 0x0000018E853ABC90>
    olive = <gshare.color.Color object at 0x0000018E845B6210>
    olivedrab = <gshare.color.Color object at 0x0000018E845B6550>
    orange = <gshare.color.Color object at 0x0000018E845B6590>
    orangered = <gshare.color.Color object at 0x0000018E845B65D0>
    orchid = <gshare.color.Color object at 0x0000018E845B6610>
    palegoldenrod = <gshare.color.Color object at 0x0000018E845B6650>
    palegreen = <gshare.color.Color object at 0x0000018EFF433B10>
    paleturquoise = <gshare.color.Color object at 0x0000018E845B6510>
    palevioletred = <gshare.color.Color object at 0x0000018E845B66D0>
    papayawhip = <gshare.color.Color object at 0x0000018E845B6710>
    peachpuff = <gshare.color.Color object at 0x0000018EFF429BD0>
    peru = <gshare.color.Color object at 0x0000018E845B6750>
    pink = <gshare.color.Color object at 0x0000018EFF429E90>
    plum = <gshare.color.Color object at 0x0000018EFF433290>
    powderblue = <gshare.color.Color object at 0x0000018EFF433B50>
    purple = <gshare.color.Color object at 0x0000018E85333B90>
    red = <gshare.color.Color object at 0x0000018E86690250>
    rosybrown = <gshare.color.Color object at 0x0000018E87A54150>
    royalblue = <gshare.color.Color object at 0x0000018E845B6410>
    saddlebrown = <gshare.color.Color object at 0x0000018E845B6790>
    salmon = <gshare.color.Color object at 0x0000018E845B6810>
    sandybrown = <gshare.color.Color object at 0x0000018E845B6850>
    seagreen = <gshare.color.Color object at 0x0000018E853ABE10>
    seashell = <gshare.color.Color object at 0x0000018E853ABB90>
    sienna = <gshare.color.Color object at 0x0000018E845B67D0>
    silver = <gshare.color.Color object at 0x0000018E845B68D0>
    skyblue = <gshare.color.Color object at 0x0000018E86690310>
    slateblue = <gshare.color.Color object at 0x0000018E845B6910>
    slategray = <gshare.color.Color object at 0x0000018E845B6890>
    slategrey = <gshare.color.Color object at 0x0000018EFF429F50>
    snow = <gshare.color.Color object at 0x0000018E8667BD10>
    springgreen = <gshare.color.Color object at 0x0000018E845B6690>
    steelblue = <gshare.color.Color object at 0x0000018E9F709490>
    tan = <gshare.color.Color object at 0x0000018E845B6990>
    teal = <gshare.color.Color object at 0x0000018E845B6A10>
    thistle = <gshare.color.Color object at 0x0000018E845B6A50>
    tomato = <gshare.color.Color object at 0x0000018E845B6A90>
    turquoise = <gshare.color.Color object at 0x0000018E845B6AD0>
    violet = <gshare.color.Color object at 0x0000018E84A52010>
    wheat = <gshare.color.Color object at 0x0000018EA05E3D50>
    white = <gshare.color.Color object at 0x0000018EFF429FD0>
    whitesmoke = <gshare.color.Color object at 0x0000018E845B6B10>
    yellow = <gshare.color.Color object at 0x0000018E845B6B50>
    yellowgreen = <gshare.color.Color object at 0x0000018E845B6B90>

    @property
    def hsv(self): ...

    @property
    def name(self): ...

    def To(self, cls): ...

    def _From(self, *args, **kwargs): ...


