"""
Module: gshare.data_cache
Dumped: 2025-12-16T22:16:58.335861
Generated by SDK Dumper
"""

# module: gshare.data_cache

# Imports
import pickle
import six2
import sys
import zlib

# Variables
GLOBAL_CACHE = {}

# Classes
class DataCache:
    def Clear(self): ...

    def GetCacheData(self): ...

    def OnlyNotify(self, key, data): ...

    def OnlyQuery(self, key): ...

    def PopQueue(self, key): ...

    def Query(self, key, callback, *args, **kwargs): ...

    def Update(self, key, data, timeout=0): ...

    def invalid(self, key): ...

class DataUploader:
    def OnTick(self): ...

    def Upload(self, item): ...

    def UploadBatch(self, items): ...

class DataWorker:
    def OnTick(self): ...

    def Start(self): ...

    def Stop(self): ...

class DataZip:
    def DataLoadZipData(self, db_data): ...

    def DataPack(self): ...

    def DataQuery(self): ...

    def DataUpdate(self, new_data): ...

class OrderedDict(dict):
    _OrderedDict__marker = <object object at 0x0000018EF52F4B90>
    get = <method 'get' of 'dict' objects>

    def _OrderedDict__update(self, other=(), /, **kwds): ...

    def clear(self): ...

    def copy(self): ...

    def fromkeys(iterable, value=None): ...

    def front_item(self): ...

    def front_key(self): ...

    def front_value(self): ...

    def items(self): ...

    def iteritems(self): yield ...

    def iterkeys(self): ...

    def itervalues(self): yield ...

    def keys(self): ...

    def move_to_end(self, key, last=True): ...

    def pop(self, key, default=<object object at 0x0000018EF52F4B90>): ...

    def popitem(self, last=True): ...

    def setdefault(self, key, default=None): ...

    def update(self, other=(), /, **kwds): ...

    def values(self): ...

class SequenceTask:
    pass

class deque:
    append = <method 'append' of 'collections.deque' objects>
    appendleft = <method 'appendleft' of 'collections.deque' objects>
    clear = <method 'clear' of 'collections.deque' objects>
    copy = <method 'copy' of 'collections.deque' objects>
    count = <method 'count' of 'collections.deque' objects>
    extend = <method 'extend' of 'collections.deque' objects>
    extendleft = <method 'extendleft' of 'collections.deque' objects>
    index = <method 'index' of 'collections.deque' objects>
    insert = <method 'insert' of 'collections.deque' objects>
    maxlen = <attribute 'maxlen' of 'collections.deque' objects>
    pop = <method 'pop' of 'collections.deque' objects>
    popleft = <method 'popleft' of 'collections.deque' objects>
    remove = <method 'remove' of 'collections.deque' objects>
    reverse = <method 'reverse' of 'collections.deque' objects>
    rotate = <method 'rotate' of 'collections.deque' objects>



