"""
Module: gshare.decorators
Dumped: 2025-12-16T22:16:58.337346
Generated by SDK Dumper
"""

# module: gshare.decorators

# Imports
import Timer
import gshare.consts
import datetime
import functools
import time

# Variables
SAFE_TAG_AVATAR = 2
SAFE_TAG_CONTROLLER = 32
SAFE_TAG_GAME = 28
SAFE_TAG_GAME_LOGIC = 16
SAFE_TAG_HALL = 7
SAFE_TAG_OUT_GAME = 1
SAFE_TAG_PLAYER = 8
SAFE_TAG_PLAYING = 60
SAFE_TAG_SPACE = 4
call_until_player_ready = functools.partial(<class 'gshare.decorators.call_until'>, <function <lambda> at 0x0000018E87E2CC20>)

# Classes
class FrameLimit:
    pass

class IntervalCall:
    pass

class LimitCall:
    pass

class LimitCallLast:
    pass

class LimitCallTimes:
    pass

class MergeCall:
    pass

class MergeCallPrevious:
    pass

class cached_property:
    pass

class call_until:
    pass

class partial:
    args = <member 'args' of 'functools.partial' objects>
    func = <member 'func' of 'functools.partial' objects>
    keywords = <member 'keywords' of 'functools.partial' objects>



# Functions
def DelayCall(delay=0): ...
def DelayCallWithKeyFunc(delay=0, delay_key_func=None): ...
def HallDelayCall(delay=0): ...
def ProfileFunc(func): ...
def SafeDelayCall(delay=0): ...
def SpaceCachingSkip(func): ...
def TagSafeCall(tag, error_cb=None): ...
def TimerCb(interval=-1, timer_name=None, is_repeat=False, stop_cond_func=None): ...
def TimerCbUINode(interval=-1, timer_name=None, is_repeat=False, stop_cond_func=None): ...
def VisibleCall(is_visible=True): ...
def _cb_once(self, func, timer_name, args, kwargs): ...
def _cb_repeat(self, func, timer_name, stop_cond_func, args, kwargs): ...
def _inner_ret(func, timer_name, is_repeat, interval, _cb): ...
def _start_timer(self, interval, _timer_name, is_repeat, cb, args, kwargs): ...
def _stop_timer(self, timer_name): ...
def cache_then_run_after(delay=0): ...
def destroyed_protect(func): ...
def interval_call(interval): ...
def log_invoke(func): ...
def rpc_frequency_limit(cd, prompt=0, limit=1): ...
def run_once_in_a_frame(func): ...
def space_needed(func): ...
def with_tag(*args): ...

