"""
Module: gshare.effect_util
Dumped: 2025-12-16T22:16:58.340302
Generated by SDK Dumper
"""

# module: gshare.effect_util

# Imports
import MCharacter
import MEngine
import gclient.framework.util.MHelper
import MObject
import MType
import Timer
import gclient.cconst
import gshare.consts
import gclient.data.effect_data
import gshare.formula
import functools
import gclient.data.gun_skin_template_data
import gclient.data.material_type_data
import math
import random
import gclient.data.random_effect_data
import gclient.framework.util.replay_util
import six2
import switches
import time
import gclient.data.weapon_data
import gshare.weapon_util

# Variables
HIT_EFFECT_FORCE_REPLACE_MATERIALS = {1002}
HitEffectMinInterval = -0.4
HitEffectRecords = defaultdict(<class 'float'>, {})
LocalConfig = <gclient.config._LocalConfig object at 0x0000018E84E70F50>

# Classes
class EPerformanceLevel(enum):
    LEVEL_0 = 0
    LEVEL_1 = 1
    LEVEL_2 = 2
    LEVEL_3 = 3
    LEVEL_4 = 4
    LEVEL_5 = 5
    LEVEL_HIGHEST = 10
    name_to_values = {'LEVEL_0': 0, 'LEVEL_1': 1, 'LEVEL_2': 2, 'LEVEL_3': 3, 'LEVEL_4': 4, 'LEVEL_5': 5, 'LEVEL_HIGHEST': 10}
    value_to_names = {0: 'LEVEL_0', 1: 'LEVEL_1', 2: 'LEVEL_2', 3: 'LEVEL_3', 4: 'LEVEL_4', 5: 'LEVEL_5', 10: 'LEVEL_HIGHEST'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class defaultdict(dict):
    clear = <method 'clear' of 'dict' objects>
    copy = <method 'copy' of 'collections.defaultdict' objects>
    default_factory = <member 'default_factory' of 'collections.defaultdict' objects>
    fromkeys = <built-in method fromkeys of type object at 0x00007FF75EB17CC0>
    get = <method 'get' of 'dict' objects>
    items = <method 'items' of 'dict' objects>
    keys = <method 'keys' of 'dict' objects>
    pop = <method 'pop' of 'dict' objects>
    popitem = <method 'popitem' of 'dict' objects>
    setdefault = <method 'setdefault' of 'dict' objects>
    update = <method 'update' of 'dict' objects>
    values = <method 'values' of 'dict' objects>


class deque:
    append = <method 'append' of 'collections.deque' objects>
    appendleft = <method 'appendleft' of 'collections.deque' objects>
    clear = <method 'clear' of 'collections.deque' objects>
    copy = <method 'copy' of 'collections.deque' objects>
    count = <method 'count' of 'collections.deque' objects>
    extend = <method 'extend' of 'collections.deque' objects>
    extendleft = <method 'extendleft' of 'collections.deque' objects>
    index = <method 'index' of 'collections.deque' objects>
    insert = <method 'insert' of 'collections.deque' objects>
    maxlen = <attribute 'maxlen' of 'collections.deque' objects>
    pop = <method 'pop' of 'collections.deque' objects>
    popleft = <method 'popleft' of 'collections.deque' objects>
    remove = <method 'remove' of 'collections.deque' objects>
    reverse = <method 'reverse' of 'collections.deque' objects>
    rotate = <method 'rotate' of 'collections.deque' objects>



# Functions
def ClearWorldEffect(effect): ...
def ClearWorldEffectImmediately(effect_id): ...
def ConfigBallisticEffect(ballistic_effect_id, is_ads, bullet_speed, hit_dis, is_fps_ballistic=True, gun_type=None, custom_scale=None): ...
def GetHitPosFromTarget(target, hit_pos, hit_normal): ...
def GetRandomAdsBallisticStartPos(muzzle_trans, radius, angle): ...
def GetWorldEffectEntity(effect_id): ...
def PlayBallisticEffect(caster, spell_id, ballistic_effect, simple_version, context=None, init_context=False, use_context=False): ...
def PlayBloodDecalEffect(target, hit_pos, hit_dir): ...
def PlayHitEffect(caster, spell_id, hit_effect, is_immune=False): ...
def PreprocessRandomEffectCache(random_cache, pattern): ...
def TestTpsballistic(): ...
def WarpperPlayEffectInWorld(effect_id, pos, time=-1, insure_play=False, sound_event_id=None): ...
def WarpperPlayEffectInWorld2(effect_id, trans, time=-1, hook_suffix=None, insure_play=False): ...
def WrapperHitEffectResult(target, hit_pos, hit_normal, hit_material_type, hit_dir, caster, weapon_id, effect_id=0, extra_effect_id=None): ...

