"""
Module: gshare.exp_util
Dumped: 2025-12-16T22:16:58.347023
Generated by SDK Dumper
"""

# module: gshare.exp_util

# Imports
import gclient.data.level_exp_data
import six2

# Variables
COMPONENT = 'Client'
MAX_EXP = 999999999
MIN_LEVEL = 1

# Functions
def CalLevelAndExpForCurExp(exp): ...
def GetCurExpAndTargetExpByLevelAndExp(exp, level): ...
def GetMaxLevel(): ...
def GetTotalUpgradeExpByCurLevel(level): ...

