"""
Module: gshare.fsm
Dumped: 2025-12-16T22:16:58.356194
Generated by SDK Dumper
"""

# module: gshare.fsm

# Imports
import six2

# Variables
COMPONENT = 'Client'

# Classes
class FiniteFsmStateMachine:
    def FSMBootstrap(self, fsm_state=None, *args, **kwargs): ...

    def FSMForceTransfer(self, fsm_state, *args, **kwargs): ...

    def FSMGetHandler(self, fsm_state, stage): ...

    def FSMShutdown(self): ...

    def FSMTick(self, delta): ...

    def FSMTransfer(self, fsm_state, *args, **kwargs): ...

class FiniteStateMachine:
    def FSMBootstrap(self, state=None, *args, **kwargs): ...

    def FSMForceTransfer(self, state, *args, **kwargs): ...

    def FSMGetHandler(self, state, stage): ...

    def FSMShutdown(self): ...

    def FSMTick(self, delta): ...

    def FSMTransfer(self, state, *args, **kwargs): ...


# Functions
def StateWrapper(cls): ...

