"""
Module: gshare.hall_box_util
Dumped: 2025-12-16T22:16:58.385550
Generated by SDK Dumper
"""

# module: gshare.hall_box_util

# Imports
import gclient.data.all_gain_box_data
import gclient.data.box_fixed_reward_data
import gclient.data.box_probability_show_data
import gclient.data.choose_box_data
import gshare.consts
import gshare.hall_item_util
import gclient.gamesystem.uihall.hall_ui_util
import gclient.data.lobby_item_data
import gclient.data.random_box_data
import six2
import sys
import gclient.data.unique_random_box_data
import gclient.data.unique_random_box_guaranteed_data

# Classes
class defaultdict(dict):
    clear = <method 'clear' of 'dict' objects>
    copy = <method 'copy' of 'collections.defaultdict' objects>
    default_factory = <member 'default_factory' of 'collections.defaultdict' objects>
    fromkeys = <built-in method fromkeys of type object at 0x00007FF75EB17CC0>
    get = <method 'get' of 'dict' objects>
    items = <method 'items' of 'dict' objects>
    keys = <method 'keys' of 'dict' objects>
    pop = <method 'pop' of 'dict' objects>
    popitem = <method 'popitem' of 'dict' objects>
    setdefault = <method 'setdefault' of 'dict' objects>
    update = <method 'update' of 'dict' objects>
    values = <method 'values' of 'dict' objects>



# Functions
def GetBoxDataForWarehouse(item_proto): ...
def GetItemListFromTreasureBox(item_proto): ...
def GetMustRewardBoxData(item_proto, mall_count=1): ...
def GetTreasureChooseBoxChooseLimit(item_proto): ...
def GetUniqueBoxGuranteeItemData(box_item_id): ...
def GetUniqueRandomDropBoxRewardDict(group_id): ...
def IsAvatarHasItem(avatar, item_id, include_experience_item=False, include_upgrade_item=False): ...

