"""
Module: gshare.http
Dumped: 2025-12-16T22:16:58.387502
Generated by SDK Dumper
"""

# module: gshare.http

# Imports
import time

# Variables
IPV4_IPV6_ANY = 3

# Classes
class BHttpRequest:
    pass

class HttpClient(SimpleAsyncBHTTPClient):
    _callback = <gshare.async_util.AsyncDescriptor object at 0x0000018EA31C53D0>
    clients = set()

    def http_request(self, request, timeout, callback, protocols=3): ...

class HttpRequest(BHttpRequest):
    def set_info(self, callback, timeout, ipv, expired_time, left_retry): ...

class SimpleAsyncBHTTPClient:
    clients = set()

    def http_request(self, request, timeout, callback, protocols=3): ...


# Functions
def Async(tag=0): ...

