"""
Module: gshare.iairdrop
Dumped: 2025-12-16T22:16:58.402142
Generated by SDK Dumper
"""

# module: gshare.iairdrop

# Imports
import MType
import gshare.consts
import gclient.data.scene_node_data
import six2

# Variables
AIRDROP_WITH_SPECIAL_MODEL = {16, 11}
AIRDROP_WITH_SPECIAL_MODEL_CREATE_TIPS = {11: 1393, 16: 1402, 15: 1402}
AIRDROP_WITH_SUBITEMS_KIND = {7, 8, 11, 12, 15, 16}
COMPONENT = 'Client'
PARACHUTE_OFF_DISTANCE = 30

# Classes
class AirdropKind(enum):
    BLEACH = 15
    COINS_SUPPLY = 9
    CRYSTAL_GAUNTLET = 16
    CRYSTAL_SWORD = 11
    ELITE = 14
    HALL_PACKAGE = 6
    ITEM_SUPPLY = 7
    LITI = 12
    SQUAD_FIGHT = 8
    SYSTEM = 2
    name_to_values = {'SYSTEM': 2, 'HALL_PACKAGE': 6, 'ITEM_SUPPLY': 7, 'SQUAD_FIGHT': 8, 'COINS_SUPPLY': 9, 'CRYSTAL_SWORD': 11, 'LITI': 12, 'ELITE': 14, 'BLEACH': 15, 'CRYSTAL_GAUNTLET': 16}
    value_to_names = {2: 'SYSTEM', 6: 'HALL_PACKAGE', 7: 'ITEM_SUPPLY', 8: 'SQUAD_FIGHT', 9: 'COINS_SUPPLY', 11: 'CRYSTAL_SWORD', 12: 'LITI', 14: 'ELITE', 15: 'BLEACH', 16: 'CRYSTAL_GAUNTLET'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class AirdropLandTag(enum):
    Landed = 2
    Normal = 0
    ParachuteOff = 1
    name_to_values = {'Normal': 0, 'ParachuteOff': 1, 'Landed': 2}
    value_to_names = {0: 'Normal', 1: 'ParachuteOff', 2: 'Landed'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class AirdropSlotUsage(enum):
    Drop = 2
    Replace = 1
    name_to_values = {'Replace': 1, 'Drop': 2}
    value_to_names = {1: 'Replace', 2: 'Drop'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class CombatItems(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.icombat_item.ICombatItem'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def Add(self, item): ...

    def Get(self, guid): ...

    def Has(self, guid): ...

    def Remove(self, guid): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class CustomIntMapType(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'int'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class CustomListType(area_list):
    IS_CUSTOM_TYPE = True
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>


class CustomMapType(area_map):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class IAirdrop:
    MAP_TAG_ID_MAP = {2: 42, 6: 42, 7: 59, 8: 66, 9: 204, 11: 10004, 12: 10006, '2_6400': 94, 14: 97, 15: 10008, 16: 10010}
    SCENE_NODE_ID_MAP = {2: 3, 6: 3, 7: 6, 8: 14, 9: 25, 11: 28, 12: 34, '2_6400': 50, 14: 52, 15: 56, 16: 59}

    def GetMapTagId(self, marker=None): ...

    def GetMarkPosition(self): ...

    def GetSceneNodeId(self, marker=None): ...

    def IsEliteAirdrop(self): ...

class PropertyMetaClass(type):
    mro = <method 'mro' of 'type' objects>


class enum:
    name_to_values = {}
    value_to_names = {}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...


# Functions
def Property(name, default, flag=2): ...

