"""
Module: gshare.ibuff
Dumped: 2025-12-16T22:16:58.413673
Generated by SDK Dumper
"""

# module: gshare.ibuff

# Imports
import gclient.data.buff_data
import six2
import sys
import time

# Variables
CLIENT_BUFF_BASE = 1000
COMPONENT = 'Client'
TickInterval = 0.2

# Classes
class BuffCategory(CustomMapType):
    CALLBACK = {'add': 'OnAddBuffCategory', 'remove': 'OnRemoveBuffCategory'}
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'common.classutils.CustomMapType'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def Add(self, buff): ...

    def Remove(self, buff): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class BuffCategoryShadow(CustomMapType):
    CALLBACK = {'add': 'OnAddBuffCategory', 'remove': 'OnRemoveBuffCategory'}
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'common.classutils.CustomMapType'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def Add(self, buff): ...

    def Remove(self, buff): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class BuffConflictRule(enum):
    COEXIST = 0
    LATEST = 1
    name_to_values = {'COEXIST': 0, 'LATEST': 1}
    value_to_names = {0: 'COEXIST', 1: 'LATEST'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class BuffEffect(enum):
    ANTI_RESTORE_ARMOR = 'ANTI_RESTORE_ARMOR'
    ANTI_RESTORE_HP = 'ANTI_RESTORE_HP'
    ANTI_SPRINT = 'ANTI_SPRINT'
    BURN = 'BURN'
    DYING_DECREASE_HP = 'DYING_DECREASE_HP'
    INVINCIBLE = 'INVINCIBLE'
    RESTORE_ARMOR = 'RESTORE_ARMOR'
    RESTORE_HP = 'RESTORE_HP'
    name_to_values = {'RESTORE_HP': 'RESTORE_HP', 'RESTORE_ARMOR': 'RESTORE_ARMOR', 'ANTI_RESTORE_HP': 'ANTI_RESTORE_HP', 'ANTI_RESTORE_ARMOR': 'ANTI_RESTORE_ARMOR', 'INVINCIBLE': 'INVINCIBLE', 'DYING_DECREASE_HP': 'DYING_DECREASE_HP', 'BURN': 'BURN', 'ANTI_SPRINT': 'ANTI_SPRINT'}
    value_to_names = {'RESTORE_HP': 'RESTORE_HP', 'RESTORE_ARMOR': 'RESTORE_ARMOR', 'ANTI_RESTORE_HP': 'ANTI_RESTORE_HP', 'ANTI_RESTORE_ARMOR': 'ANTI_RESTORE_ARMOR', 'INVINCIBLE': 'INVINCIBLE', 'DYING_DECREASE_HP': 'DYING_DECREASE_HP', 'BURN': 'BURN', 'ANTI_SPRINT': 'ANTI_SPRINT'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class BuffEffectCateory(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'common.classutils.CustomMapType'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def Add(self, buff): ...

    def Remove(self, buff): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class BuffEffectCateoryShadow(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'common.classutils.CustomMapType'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def Add(self, buff): ...

    def Remove(self, buff): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class BuffExtraInfo(enum):
    NeedCasterId = 1
    NeedCasterTeamId = 2
    NeedUnknown = 0
    name_to_values = {'NeedUnknown': 0, 'NeedCasterId': 1, 'NeedCasterTeamId': 2}
    value_to_names = {0: 'NeedUnknown', 1: 'NeedCasterId', 2: 'NeedCasterTeamId'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class BuffFactory:
    def CreateSimple(kind, duration, level=1, stack=1): ...

class BuffKind(enum):
    FIREWALL = 1028
    FLASH_BOMB = 7
    KRAKEN = 1010
    STEALTH_EFFECT = 14
    XRAY_BOMB = 6
    name_to_values = {'XRAY_BOMB': 6, 'FLASH_BOMB': 7, 'STEALTH_EFFECT': 14, 'KRAKEN': 1010, 'FIREWALL': 1028}
    value_to_names = {6: 'XRAY_BOMB', 7: 'FLASH_BOMB', 14: 'STEALTH_EFFECT', 1010: 'KRAKEN', 1028: 'FIREWALL'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class ClientBuffFactory:
    Cache = defaultdict(<class 'list'>, {})

    def CreateRestoreSsp(duration, number): ...

    def CreateSimple(kind, duration, level=1): ...

    def CreateSuperSprint(duration): ...

    def EnqueueCache(kind, buff): ...

class ClientBuffKind(enum):
    ANTI_RESTORE_SSP = 1001
    FeelSurmount1 = 1004
    FeelSurmount1Forever = 1005
    FeelSurmount3 = 1003
    RESTORE_SSP = 1000
    SUPER_SPRINT = 1002
    name_to_values = {'RESTORE_SSP': 1000, 'ANTI_RESTORE_SSP': 1001, 'SUPER_SPRINT': 1002, 'FeelSurmount3': 1003, 'FeelSurmount1': 1004, 'FeelSurmount1Forever': 1005}
    value_to_names = {1000: 'RESTORE_SSP', 1001: 'ANTI_RESTORE_SSP', 1002: 'SUPER_SPRINT', 1003: 'FeelSurmount3', 1004: 'FeelSurmount1', 1005: 'FeelSurmount1Forever'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class CustomListType(area_list):
    IS_CUSTOM_TYPE = True
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>


class CustomMapType(area_map):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class IBuff(CustomMapType):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    @property
    def buff_owner(self): ...

    @property
    def buff_owner_team(self): ...

    @property
    def effect(self): ...

    @property
    def fl_degree(self): ...

    @property
    def number(self): ...

    @property
    def proto(self): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class IBuffShadow(CustomMapType):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    @property
    def buff_owner(self): ...

    @property
    def buff_owner_team(self): ...

    @property
    def effect(self): ...

    @property
    def fl_degree(self): ...

    @property
    def number(self): ...

    @property
    def proto(self): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class IBuffs(CustomMapType):
    CALLBACK = {'add': 'OnAddBuff', 'remove': 'OnRemoveBuff'}
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.ibuff.IBuff'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def AddBuff(self, buff): ...

    def Clear(self): ...

    def GetBuff(self, guid): ...

    def GetBuffsByEffect(self, effect): ...

    def GetBuffsByType(self, kind): ...

    def GetBuffsByTypeFromCategory(self, kind): ...

    def HasBuffsByEffect(self, effect): ...

    def HasBuffsByType(self, kind): ...

    def RemoveBuff(self, guid): ...

    def RemoveBuffsByEffect(self, effect): ...

    def RemoveBuffsByType(self, kind): ...

    def RemoveExpires(self): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class IBuffsShadow(CustomMapType):
    CALLBACK = {'add': 'OnAddBuff', 'remove': 'OnRemoveBuff'}
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.ibuff.IBuffShadow'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def AddBuff(self, buff): ...

    def Clear(self): ...

    def GetBuff(self, guid): ...

    def GetBuffsByEffect(self, effect): ...

    def GetBuffsByType(self, kind): ...

    def GetBuffsByTypeFromCategory(self, kind): ...

    def HasBuffsByEffect(self, effect): ...

    def HasBuffsByType(self, kind): ...

    def RemoveBuff(self, guid): ...

    def RemoveBuffsByEffect(self, effect): ...

    def RemoveBuffsByType(self, kind): ...

    def RemoveExpires(self): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class IdManager:
    def bytes2id(bytes): ...

    def genid(): ...

    def id2bytes(uid): ...

    def id2str(uid): ...

    def is_valid_id(entityid): ...

    def str2id(string): ...

class defaultdict(dict):
    clear = <method 'clear' of 'dict' objects>
    copy = <method 'copy' of 'collections.defaultdict' objects>
    default_factory = <member 'default_factory' of 'collections.defaultdict' objects>
    fromkeys = <built-in method fromkeys of type object at 0x00007FF75EB17CC0>
    get = <method 'get' of 'dict' objects>
    items = <method 'items' of 'dict' objects>
    keys = <method 'keys' of 'dict' objects>
    pop = <method 'pop' of 'dict' objects>
    popitem = <method 'popitem' of 'dict' objects>
    setdefault = <method 'setdefault' of 'dict' objects>
    update = <method 'update' of 'dict' objects>
    values = <method 'values' of 'dict' objects>


class enum:
    name_to_values = {}
    value_to_names = {}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...


# Functions
def ExtraProperty(name, default): ...
def Property(name, default, flag=2): ...

