"""
Module: gshare.icc_voice
Dumped: 2025-12-16T22:16:58.415288
Generated by SDK Dumper
"""

# module: gshare.icc_voice

# Variables
CC_NAME = {5: 'team', 1: 'team', 2: 'nearby', 3: 'ridicule', 6: 'room'}
CC_Nearby_Maxuser = 100
CC_Nearby_Radius = 50
CC_Nearby_Radius_Map = {1400: 100}
IG_CHANNEL_LIST = [1, 2, 3, 4]

# Classes
class CCChannelType(enum):
    CombatHallTeam = 4
    CombatTeam = 1
    HallTeam = 5
    KillRidicule = 3
    Nearby = 2
    NoMike = 0
    Room = 6
    name_to_values = {'NoMike': 0, 'CombatTeam': 1, 'Nearby': 2, 'KillRidicule': 3, 'CombatHallTeam': 4, 'HallTeam': 5, 'Room': 6}
    value_to_names = {0: 'NoMike', 1: 'CombatTeam', 2: 'Nearby', 3: 'KillRidicule', 4: 'CombatHallTeam', 5: 'HallTeam', 6: 'Room'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class enum:
    name_to_values = {}
    value_to_names = {}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...


