"""
Module: gshare.ichat
Dumped: 2025-12-16T22:16:58.418367
Generated by SDK Dumper
"""

# module: gshare.ichat

# Imports
import gclient.data.chat_language_data
import copy
import six2

# Variables
CHANNEL = 2
CHAT_BUBBLES = 14
CLAN_CHANNEL_CD = 60
COMPONENT = 'Client'
CONTENT = 3
ChatChannelToBanType = {1: 4, 2: 4, 3: 2, 4: 8, 6: 4, 7: 2, 8: 2}
EXTRA = 12
FROM = 6
GUID = 1
HEAD_FRAME = 13
IG_MESSAGE_TYPES = (3, 2, 4)
LANG_CHANNEL_CD = 10
LANG_CHANNEL_HEAD = 'Lang_'
MSG_TYPE = 10
NAME = 7
OFFICIAL_HEAD = 9
SEGMENT = 8
SEND_TIME = 11
SHARE_MSG_TYPES = (15, 14, 13)
SHOW_MEDAL = 15
SOUND = 4
TO = 5
VERSION = 0
WORLD_CHANNEL_CD = 10
channel = 106
cur_version = 17
key = 'th'
key_num = 16
msg_sample = [17, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
name = 'Lang_th'
proto = {'id': 'th', 'channel': 106, 'channel_pic': 11320}

# Classes
class AIRole(enum):
    assistant = 3
    name_to_values = {'system': 1, 'user': 2, 'assistant': 3}
    system = 1
    user = 2
    value_to_names = {1: 'system', 2: 'user', 3: 'assistant'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class BanChatType(enum):
    Friend = 8
    Team = 4
    World = 2
    name_to_values = {'World': 2, 'Team': 4, 'Friend': 8}
    value_to_names = {2: 'World', 4: 'Team', 8: 'Friend'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class ChatChannel(enum):
    AI = 21
    Clan = 8
    CombatTeam = 1
    HallFriend = 4
    HallRecruit = 6
    HallTeam = 2
    HallWorld = 3
    Lang_ar = 108
    Lang_en = 102
    Lang_es = 103
    Lang_in = 105
    Lang_ja = 110
    Lang_pt = 104
    Lang_ru = 107
    Lang_th = 106
    Lang_tr = 111
    Lang_tw = 109
    Lang_zh = 101
    Room = 7
    System = 5
    name_to_values = {'CombatTeam': 1, 'HallTeam': 2, 'HallWorld': 3, 'HallFriend': 4, 'System': 5, 'HallRecruit': 6, 'Room': 7, 'Clan': 8, 'AI': 21, 'Lang_in': 105, 'Lang_ar': 108, 'Lang_en': 102, 'Lang_es': 103, 'Lang_ja': 110, 'Lang_zh': 101, 'Lang_ru': 107, 'Lang_pt': 104, 'Lang_tw': 109, 'Lang_tr': 111, 'Lang_th': 106}
    value_to_names = {1: 'CombatTeam', 2: 'HallTeam', 3: 'HallWorld', 4: 'HallFriend', 5: 'System', 6: 'HallRecruit', 7: 'Room', 8: 'Clan', 21: 'AI', 105: 'Lang_in', 108: 'Lang_ar', 102: 'Lang_en', 103: 'Lang_es', 110: 'Lang_ja', 101: 'Lang_zh', 107: 'Lang_ru', 104: 'Lang_pt', 109: 'Lang_tw', 111: 'Lang_tr', 106: 'Lang_th'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class CustomIntMapType(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'int'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class CustomListType(area_list):
    IS_CUSTOM_TYPE = True
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>


class CustomMapType(area_map):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class IdManager:
    def bytes2id(bytes): ...

    def genid(): ...

    def id2bytes(uid): ...

    def id2str(uid): ...

    def is_valid_id(entityid): ...

    def str2id(string): ...

class MessageType(enum):
    ClanAch = 11
    ClanAchLike = 12
    ClanJion = 9
    ClanQuick = 10
    IgMarkMsg = 3
    IgRequestItem = 8
    IgShortMsg = 2
    KillMoments = 16
    NeedItem = 17
    Normal = 1
    Recruit = 6
    ShareClan = 15
    ShareCombat = 13
    ShareGun = 14
    SharePanPan = 18
    SystemHorn = 5
    TeamReservation = 4
    Voice = 7
    name_to_values = {'Normal': 1, 'IgShortMsg': 2, 'IgMarkMsg': 3, 'TeamReservation': 4, 'SystemHorn': 5, 'Recruit': 6, 'Voice': 7, 'IgRequestItem': 8, 'ClanJion': 9, 'ClanQuick': 10, 'ClanAch': 11, 'ClanAchLike': 12, 'ShareCombat': 13, 'ShareGun': 14, 'ShareClan': 15, 'KillMoments': 16, 'NeedItem': 17, 'SharePanPan': 18}
    value_to_names = {1: 'Normal', 2: 'IgShortMsg', 3: 'IgMarkMsg', 4: 'TeamReservation', 5: 'SystemHorn', 6: 'Recruit', 7: 'Voice', 8: 'IgRequestItem', 9: 'ClanJion', 10: 'ClanQuick', 11: 'ClanAch', 12: 'ClanAchLike', 13: 'ShareCombat', 14: 'ShareGun', 15: 'ShareClan', 16: 'KillMoments', 17: 'NeedItem', 18: 'SharePanPan'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class enum:
    name_to_values = {}
    value_to_names = {}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...


# Functions
def IsLangChannel(channel): ...
def NewMsg(): ...
def NewRecruitMsg(avatar, extra): ...
def NewSystemChat(content, code, args, limit_info=None, channel=5, msg_type=5, **extras): ...
def NewSystemHorn(content, limit_info): ...
def Property(name, default, flag=2): ...

