"""
Module: gshare.iclan
Dumped: 2025-12-16T22:16:58.430229
Generated by SDK Dumper
"""

# module: gshare.iclan

# Imports
import gclient.data.clan_apply_qualifying_data
import gclient.data.clan_style_data
import gshare.consts
import gclient.data.game_const_data
import six2
import time

# Variables
AGREE_MIN_ROLE = 2
APPLY_LIMIT = 50
APPLY_LIST_LIMIT = 120
ASSIGN_CEO_MIN_JOIN_TIME = 0
AgreeToApplyErrno = {0: 867, 876: 862, 878: 853}
ApplyConfig = {'apply_verify': (<class 'int'>, None), 'apply_level': (<class 'int'>, <function <lambda> at 0x0000018E846C99E0>), 'apply_score': (<class 'int'>, <function <lambda> at 0x0000018E846C9A80>)}
BOARD_CHANGE_CD = 60
BOARD_MAX_LENGTH = 100
BriefFields = {'id': '', 'no': 0, 'name': '', 'icon': 0, 'country_icon': 0, 'board': '', 'styles': [], 'online': 0, 'apply_verify': 0, 'apply_level': -1, 'apply_score': -1, 'current_members': 0, 'max_members': 0, 'member_info': {}, 'creator': '', 'change_name_time': 0}
BriefQueryFields = {'id': 1, 'no': 1, 'name': 1, 'icon': 1, 'country_icon': 1, 'language': 1, 'styles': 1, 'board': 1, 'ceo': 1, 'apply_verify': 1, 'apply_level': 1, 'apply_score': 1, 'current_members': 1, 'online': 1, 'total_scores': 1, 'create_time': 1, 'members': 1}
CHANGE_NAME_CD = 2592000
CHANGE_NAME_COST = 500
CHAT_MSG_LIMIT = 20
CHAT_MSG_TIMEOUT = 2592000
CHECK_CLAN_MEMBER_VAILD = 2
CLAN_ALL_FILTERS = {'apply_verify': (<class 'int'>, <function <lambda> at 0x0000018E846C9D00>), 'apply_score': (<class 'int'>, <function <lambda> at 0x0000018E846C9F80>)}
CLAN_DEFAULT_COUNTRY_ICON = 1
CLAN_MAIL_NUM = 2
CLAN_MAX_MEMBERS = 30
CLAN_NO_BASE = 101350
CLAN_ROLE_MAX_COUNT = {2: 1, 4: 1, 8: 1}
COMPONENT = 'Client'
CREATE_MIN_LEVEL = 1
CREATE_POSSIBLE_FIELDS = {'id': <class 'str'>, 'name': <class 'str'>, 'icon': <class 'int'>, 'country_icon': <class 'int'>, 'board': <class 'str'>, 'styles': <class 'list'>, 'region_pids': <class 'list'>, 'money_type': <class 'int'>, 'apply_score': <class 'int'>, 'apply_level': <class 'int'>, 'apply_verify': <class 'int'>, 'language': <class 'str'>, 'country_code': <class 'str'>}
CREATE_REQUIRED_FIELDS = {'name': <class 'str'>, 'icon': <class 'int'>, 'country_icon': <class 'int'>, 'board': <class 'str'>, 'styles': <class 'list'>, 'region_pids': <class 'list'>, 'money_type': <class 'int'>, 'apply_score': <class 'int'>, 'apply_level': <class 'int'>, 'apply_verify': <class 'int'>, 'language': <class 'str'>, 'country_code': <class 'str'>}
DataFields = {1: {'id': '', 'no': 0, 'name': '', 'icon': 0, 'country_icon': 0, 'board': '', 'styles': [], 'online': 0, 'apply_verify': 0, 'apply_level': -1, 'apply_score': -1, 'current_members': 0, 'max_members': 0, 'member_info': {}, 'creator': '', 'change_name_time': 0, 'ceo': {}}, 2: {'id': '', 'no': 0, 'name': '', 'icon': 0, 'country_icon': 0, 'board': '', 'styles': [], 'online': 0, 'apply_verify': 0, 'apply_level': -1, 'apply_score': -1, 'current_members': 0, 'max_members': 0, 'member_info': {}, 'creator': '', 'change_name_time': 0, 'ceo': {}, 'appliers': {}, 'shield_appliers': {}, 'mail_sent': 0}, 8: {'id': '', 'no': 0, 'name': '', 'icon': 0, 'country_icon': 0, 'board': '', 'styles': [], 'online': 0, 'apply_verify': 0, 'apply_level': -1, 'apply_score': -1, 'current_members': 0, 'max_members': 0, 'member_info': {}, 'creator': '', 'change_name_time': 0, 'members': {}, 'managers_info': {}}, 3: {'members': {}, 'current_members': 0}, 4: {'members': {}, 'player_info': {}}, 7: {'members': {}, 'player_info': {}, 'appliers': {}, 'shield_appliers': {}}, 5: {'id': '', 'no': 0, 'name': '', 'icon': 0, 'country_icon': 0, 'board': '', 'styles': [], 'online': 0, 'apply_verify': 0, 'apply_level': -1, 'apply_score': -1, 'current_members': 0, 'max_members': 0, 'member_info': {}, 'creator': '', 'change_name_time': 0, 'ceo': {}, 'total_scores': {}}, 6: {'members': {}, 'player_info': {}, 'ach_logs': []}}
EClanFilter_APPLYABLE = 'applyable'
EClanFilter_FULL = 'full'
EClanFilter_LANGUAGE = 'language'
EClanFilter_LEVEL = 'apply_level'
EClanFilter_REGION = 'region_pids'
EClanFilter_SCORE = 'apply_score'
EClanFilter_STYLE = 'styles'
EClanFilter_VERIFY = 'apply_verify'
INVITE_MIN_ROLE = 1
JOURNAL_EXPIRE = 604800.0
JOURNAL_MAX_COUNT = 50
KICK_MIN_ROLE = 2
LeaveToKickErrno = {0: 0, 1: 906, 2: 906}
MAIL_BODY_MAX_LENGTH = 450
MAIL_OVERDUE = 0
MANAGER_MIN_ROLE = 2
MANAGER_MODIFY_NAME_TIME = 259200
MAX_STYLE_NUM = 4
NAME_MAX_LENGTH = 14
NAME_MIN_LENGTH = 3
PAGE_SIZE = 10
SyncFields = {'id': '', 'no': -1, 'name': '', 'icon': 0, 'role': 0, 'jt': 0.0}
USURP_FINAL_DAYS = 15
USURP_MIN_ROLE = 1
USURP_WARNING_DAYS = 10

# Classes
class AgreeErrno(enum):
    ALREADY = 878
    FORBIDDEN = 875
    FULL = 876
    NOT_FOUND = 877
    SUCCESS = 0
    name_to_values = {'SUCCESS': 0, 'FULL': 876, 'ALREADY': 878, 'NOT_FOUND': 877, 'FORBIDDEN': 875}
    value_to_names = {0: 'SUCCESS', 876: 'FULL', 878: 'ALREADY', 877: 'NOT_FOUND', 875: 'FORBIDDEN'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class ApplyErrno(enum):
    ALREADY = 2
    APPLY_AGREED = 867
    APPLY_LIST_LIMIT = 866
    CLAN_APPLY_LIMIT = 865
    FAILED = 7
    FULL = 862
    HAS_CLAN = 853
    INVALID_CLAN = 970
    INVALID_INVITER = 996
    INVALID_REGION = 12
    LIMIT_LEVEL = 861
    LIMIT_SCORE = 958
    SUCCESS = 0
    VERIFY = 863
    name_to_values = {'SUCCESS': 0, 'APPLY_AGREED': 867, 'ALREADY': 2, 'FULL': 862, 'LIMIT_LEVEL': 861, 'LIMIT_SCORE': 958, 'HAS_CLAN': 853, 'FAILED': 7, 'VERIFY': 863, 'APPLY_LIST_LIMIT': 866, 'CLAN_APPLY_LIMIT': 865, 'INVALID_REGION': 12, 'INVALID_CLAN': 970, 'INVALID_INVITER': 996}
    value_to_names = {0: 'SUCCESS', 867: 'APPLY_AGREED', 2: 'ALREADY', 862: 'FULL', 861: 'LIMIT_LEVEL', 958: 'LIMIT_SCORE', 853: 'HAS_CLAN', 7: 'FAILED', 863: 'VERIFY', 866: 'APPLY_LIST_LIMIT', 865: 'CLAN_APPLY_LIMIT', 12: 'INVALID_REGION', 970: 'INVALID_CLAN', 996: 'INVALID_INVITER'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class AssignErrno(enum):
    DUPLICATED = 908
    FORBIDDEN = 875
    LIMITED = 907
    LIMIT_JOIN_TIME = 6
    NOT_ALLOWED = 909
    NOT_FOUND = 906
    NO_CLAN = 880
    SUCCESS = 0
    name_to_values = {'SUCCESS': 0, 'NO_CLAN': 880, 'NOT_FOUND': 906, 'FORBIDDEN': 875, 'LIMITED': 907, 'DUPLICATED': 908, 'LIMIT_JOIN_TIME': 6, 'NOT_ALLOWED': 909}
    value_to_names = {0: 'SUCCESS', 880: 'NO_CLAN', 906: 'NOT_FOUND', 875: 'FORBIDDEN', 907: 'LIMITED', 908: 'DUPLICATED', 6: 'LIMIT_JOIN_TIME', 909: 'NOT_ALLOWED'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class CLAN_ACH_LOG_TYPE(enum):
    ITEM_QUALITY = 4
    QUALIFYING_LEVEL = 2
    QUALIFYING_RANK = 3
    WIN = 1
    name_to_values = {'WIN': 1, 'QUALIFYING_LEVEL': 2, 'QUALIFYING_RANK': 3, 'ITEM_QUALITY': 4}
    value_to_names = {1: 'WIN', 2: 'QUALIFYING_LEVEL', 3: 'QUALIFYING_RANK', 4: 'ITEM_QUALITY'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class ChangeBoardErrno(enum):
    CD = 5
    FORBIDDEN = 875
    FREEZING = 6
    INVALID = 3
    NO_CLAN = 880
    OVER_LEN = 4
    SUCCESS = 0
    name_to_values = {'SUCCESS': 0, 'NO_CLAN': 880, 'FORBIDDEN': 875, 'INVALID': 3, 'OVER_LEN': 4, 'CD': 5, 'FREEZING': 6}
    value_to_names = {0: 'SUCCESS', 880: 'NO_CLAN', 875: 'FORBIDDEN', 3: 'INVALID', 4: 'OVER_LEN', 5: 'CD', 6: 'FREEZING'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class ChangeIconErrno(enum):
    ALREADY = 4
    FORBIDDEN = 2
    INVALID = 5
    LACK_GOLD = 3
    NO_CLAN = 1
    SUCCESS = 0
    name_to_values = {'SUCCESS': 0, 'NO_CLAN': 1, 'FORBIDDEN': 2, 'LACK_GOLD': 3, 'ALREADY': 4, 'INVALID': 5}
    value_to_names = {0: 'SUCCESS', 1: 'NO_CLAN', 2: 'FORBIDDEN', 3: 'LACK_GOLD', 4: 'ALREADY', 5: 'INVALID'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class ChangeNameErrno(enum):
    CD = 887
    DUPLICATED = 851
    FORBIDDEN = 875
    FREEZING = 8
    GM = 10
    INVALID = 850
    ITEM = 12
    LACK_ITEM = 7
    MONEY = 966
    NO_CLAN = 880
    OVER_LEN = 4
    REGION_INVALID = 856
    SUCCESS = 0
    TIMEOUT = 11
    name_to_values = {'SUCCESS': 0, 'NO_CLAN': 880, 'FORBIDDEN': 875, 'INVALID': 850, 'OVER_LEN': 4, 'DUPLICATED': 851, 'MONEY': 966, 'LACK_ITEM': 7, 'FREEZING': 8, 'CD': 887, 'GM': 10, 'TIMEOUT': 11, 'ITEM': 12, 'REGION_INVALID': 856}
    value_to_names = {0: 'SUCCESS', 880: 'NO_CLAN', 875: 'FORBIDDEN', 850: 'INVALID', 4: 'OVER_LEN', 851: 'DUPLICATED', 966: 'MONEY', 7: 'LACK_ITEM', 8: 'FREEZING', 887: 'CD', 10: 'GM', 11: 'TIMEOUT', 12: 'ITEM', 856: 'REGION_INVALID'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class ChangeStylesErrno(enum):
    FORBIDDEN = 875
    INVALID = 896
    NO_CLAN = 880
    SUCCESS = 0
    name_to_values = {'SUCCESS': 0, 'NO_CLAN': 880, 'FORBIDDEN': 875, 'INVALID': 896}
    value_to_names = {0: 'SUCCESS', 880: 'NO_CLAN', 875: 'FORBIDDEN', 896: 'INVALID'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class ClanApplySource(enum):
    CLAN_LIST = 3
    DEFAULT = 0
    MEMBER_INVITE = 2
    SEARCH = 1
    name_to_values = {'DEFAULT': 0, 'SEARCH': 1, 'MEMBER_INVITE': 2, 'CLAN_LIST': 3}
    value_to_names = {0: 'DEFAULT', 1: 'SEARCH', 2: 'MEMBER_INVITE', 3: 'CLAN_LIST'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class ClanApplys(CustomFloatMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'float'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def Add(self, guid): ...

    def Clear(self): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class ClanRole(enum):
    CEO = 8
    CHEER = 2
    NONE = 0
    STAFF = 1
    VP = 4
    name_to_values = {'NONE': 0, 'STAFF': 1, 'CHEER': 2, 'VP': 4, 'CEO': 8}
    value_to_names = {0: 'NONE', 1: 'STAFF', 2: 'CHEER', 4: 'VP', 8: 'CEO'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class ConfigureApplyErrno(enum):
    FORBIDDEN = 875
    FREEZING = 4
    INVALID_KEY = 895
    INVALID_VALUE = 896
    SUCCESS = 0
    name_to_values = {'SUCCESS': 0, 'FORBIDDEN': 875, 'INVALID_KEY': 895, 'INVALID_VALUE': 896, 'FREEZING': 4}
    value_to_names = {0: 'SUCCESS', 875: 'FORBIDDEN', 895: 'INVALID_KEY', 896: 'INVALID_VALUE', 4: 'FREEZING'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class CreateErrno(enum):
    ALREADY = 853
    CHECKSUM = 10
    CREATING = 1
    EXTRA_FIELDS = 858
    GEN_NO_ERROR = 3
    INVALID_ICON = 896
    INVALID_REGION = 856
    INVALID_STYLE = 17
    LACK_FIELDS = 6
    LEVEL = 14
    MAX_CREATINGS = 13
    MONEY = 852
    NAME_ERROR = 851
    NO_NAME = 850
    SAVE_ERROR = 8
    SUCCESS = 0
    WANT_AD_LENGTH = 12
    name_to_values = {'SUCCESS': 0, 'CREATING': 1, 'ALREADY': 853, 'GEN_NO_ERROR': 3, 'NAME_ERROR': 851, 'LACK_FIELDS': 6, 'EXTRA_FIELDS': 858, 'SAVE_ERROR': 8, 'MONEY': 852, 'CHECKSUM': 10, 'NO_NAME': 850, 'WANT_AD_LENGTH': 12, 'MAX_CREATINGS': 13, 'LEVEL': 14, 'INVALID_ICON': 896, 'INVALID_REGION': 856, 'INVALID_STYLE': 17}
    value_to_names = {0: 'SUCCESS', 1: 'CREATING', 853: 'ALREADY', 3: 'GEN_NO_ERROR', 851: 'NAME_ERROR', 6: 'LACK_FIELDS', 858: 'EXTRA_FIELDS', 8: 'SAVE_ERROR', 852: 'MONEY', 10: 'CHECKSUM', 850: 'NO_NAME', 12: 'WANT_AD_LENGTH', 13: 'MAX_CREATINGS', 14: 'LEVEL', 896: 'INVALID_ICON', 856: 'INVALID_REGION', 17: 'INVALID_STYLE'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class CustomFloatMapType(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'float'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class DataType(enum):
    ACH_LOGS = 6
    APPLY_PLAYER_INFO = 7
    BRIEF = 1
    FETCH_RECOMMENT = 5
    MANAGER = 2
    MEMBERS = 3
    PLAYER_INFO = 4
    SHARE = 8
    name_to_values = {'BRIEF': 1, 'MANAGER': 2, 'MEMBERS': 3, 'PLAYER_INFO': 4, 'FETCH_RECOMMENT': 5, 'ACH_LOGS': 6, 'APPLY_PLAYER_INFO': 7, 'SHARE': 8}
    value_to_names = {1: 'BRIEF', 2: 'MANAGER', 3: 'MEMBERS', 4: 'PLAYER_INFO', 5: 'FETCH_RECOMMENT', 6: 'ACH_LOGS', 7: 'APPLY_PLAYER_INFO', 8: 'SHARE'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class JournalType(enum):
    ASSIGN = 3
    ASSIGN_CEO = 7
    IMPEACH = 6
    JOIN = 1
    KICK = 9
    LEAVE = 2
    NONE = 0
    OFFLINE = 10
    UNLOCK_HERO = 8
    UPGRADE = 4
    USURP = 5
    name_to_values = {'NONE': 0, 'JOIN': 1, 'LEAVE': 2, 'ASSIGN': 3, 'UPGRADE': 4, 'USURP': 5, 'IMPEACH': 6, 'ASSIGN_CEO': 7, 'UNLOCK_HERO': 8, 'KICK': 9, 'OFFLINE': 10}
    value_to_names = {0: 'NONE', 1: 'JOIN', 2: 'LEAVE', 3: 'ASSIGN', 4: 'UPGRADE', 5: 'USURP', 6: 'IMPEACH', 7: 'ASSIGN_CEO', 8: 'UNLOCK_HERO', 9: 'KICK', 10: 'OFFLINE'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class KickErrno(enum):
    FAILED = 3
    FORBIDDEN = 875
    NOT_ALLOWED = 4
    NOT_FOUND = 906
    SUCCESS = 0
    name_to_values = {'SUCCESS': 0, 'NOT_FOUND': 906, 'FORBIDDEN': 875, 'FAILED': 3, 'NOT_ALLOWED': 4}
    value_to_names = {0: 'SUCCESS', 906: 'NOT_FOUND', 875: 'FORBIDDEN', 3: 'FAILED', 4: 'NOT_ALLOWED'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class LeaveErrno(enum):
    FORBIDDEN = 3
    NO_CLAN = 1
    NO_MEMBER = 2
    SUCCESS = 0
    name_to_values = {'SUCCESS': 0, 'NO_CLAN': 1, 'NO_MEMBER': 2, 'FORBIDDEN': 3}
    value_to_names = {0: 'SUCCESS', 1: 'NO_CLAN', 2: 'NO_MEMBER', 3: 'FORBIDDEN'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class SendMailErrno(enum):
    BODY_OVER_LEN = 5
    CD = 6
    FORBIDDEN = 875
    FREEZING = 7
    INVALID = 896
    NO_CLAN = 880
    NUM_LIMIT = 917
    SUCCESS = 0
    name_to_values = {'SUCCESS': 0, 'NO_CLAN': 880, 'FORBIDDEN': 875, 'INVALID': 896, 'BODY_OVER_LEN': 5, 'CD': 6, 'FREEZING': 7, 'NUM_LIMIT': 917}
    value_to_names = {0: 'SUCCESS', 880: 'NO_CLAN', 875: 'FORBIDDEN', 896: 'INVALID', 5: 'BODY_OVER_LEN', 6: 'CD', 7: 'FREEZING', 917: 'NUM_LIMIT'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class enum:
    name_to_values = {}
    value_to_names = {}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...


# Functions
def CalcClanTotalQualifyingScore(members): ...
def CalcQualifyingLevel(qualifying_match_type, qualifying_score, season=None): ...
def CheckClanApplyConditionsSatisfied(avatar, clan_info): ...
def CheckQualifyingScore(score, rank, apply_score): ...
def DecodeLogKey(log_key): ...
def EnableClan(): ...
def GenLogKey(log_type, match_type=0, any=0): ...
def GetClanQualifyingLevel(total_scores, current_members): ...
def GetClanQueryKey(page, filters, hostnum, extra=None): ...
def GetClanRecommendKey(page, filters, hostnum, extra=None): ...
def GetClanRecommendOuterLinkKey(use_filter, filters, from_open, extra=None): ...
def GetMaxQualifyingLevel(q_scores): ...
def GetQualifyingScoreLevel(avatar): ...
def IsRegionValid(region_pids): ...
def IsStyleValid(styles): ...
def MergeDict(*dicts): ...

