"""
Module: gshare.icomp_attach
Dumped: 2025-12-16T22:16:58.466341
Generated by SDK Dumper
"""

# module: gshare.icomp_attach

# Imports
import six2

# Classes
class CustomFloatListType(CustomListType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'float'>
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>


class IEntityAttachComponent:
    pass

class IEntityMasterComponent:
    pass

class PropertyMetaClass(type):
    mro = <method 'mro' of 'type' objects>



# Functions
def Property(name, default, flag=2): ...
def with_tag(*args): ...

