"""
Module: gshare.icombat_unit
Dumped: 2025-12-16T22:16:58.463414
Generated by SDK Dumper
"""

# module: gshare.icombat_unit

# Imports
import gshare.consts
import gclient.data.hero_attributes_data
import gclient.data.hero_data
import gclient.data.lobby_item_data
import six2

# Variables
COMPONENT = 'Client'

# Classes
class ArmEmoteInfos(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'common.classutils.CustomMapType'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class AttrType(enum):
    ANTI_RESTORE_HP_TIME = 7
    AmmoMaxStack = 22
    AssassinateEnergyUp = 47
    BackpackFreeSlot = 21
    BanSprint = 62
    BombBuffDuration = 18
    BombBuffRange = 17
    BombDamage = 16
    BombDamageRange = 15
    CannonDamage = 46
    CureUavCureSpeed = 42
    CureUavRangeUp = 65
    CureUavTimeUp = 66
    CureValueUp = 58
    EnergySkillChargeSpeed = 56
    EnergyValueUp = 26
    ForbidChangeWeapon = 55
    ForbidRestoreArmor = 60
    ForbidRestoreHP = 59
    FullScanTime = 43
    GasDamage = 41
    GasFiledDamage = 44
    GasRange = 40
    GasTime = 39
    Goggle = 5
    GunDamage = 23
    HeatResist = 6
    HelpOtherFinishHp = 20
    HelpOtherSpeed = 2
    Invincible = 61
    KillReward = 10
    LightRayDamage = 36
    LightRayRange = 37
    LightRayTime = 35
    MagicFieldEffectScaleX = 28
    MagicFieldEffectScaleY = 29
    MagicFieldEffectScaleZ = 30
    MaxArmor = 3
    MaxHp = 1
    MaxStack = 12
    MissileDamage = 32
    MissileStrikeCount = 31
    MoveDamageReduce = 54
    Ninja = 4
    ParanoiaDistance = 49
    ParanoiaRadius = 50
    ParanoiaTime = 51
    RecoverArmorSpeed = 19
    RecoverArmorTime = 24
    RecoverSpeed = 11
    SatelliteScanInterval = 38
    SatelliteScanRange = 34
    SatelliteScanTime = 33
    ShadowRange = 53
    ShadowTime = 52
    ShieldDuration = 27
    SkillChargeSpeed = 57
    SkillMaxCount = 64
    SkillRange = 45
    SkillRechargeTime = 13
    StorePrice = 14
    SupplyProb = 8
    TaskReward = 9
    UavRecoverArmorSpeed = 48
    UseCureItemSpeed = 63
    ZombieDamageDown = 67
    name_to_values = {'MaxHp': 1, 'HelpOtherSpeed': 2, 'MaxArmor': 3, 'Ninja': 4, 'Goggle': 5, 'HeatResist': 6, 'ANTI_RESTORE_HP_TIME': 7, 'SupplyProb': 8, 'TaskReward': 9, 'KillReward': 10, 'RecoverSpeed': 11, 'MaxStack': 12, 'SkillRechargeTime': 13, 'StorePrice': 14, 'BombDamageRange': 15, 'BombDamage': 16, 'BombBuffRange': 17, 'BombBuffDuration': 18, 'RecoverArmorSpeed': 19, 'HelpOtherFinishHp': 20, 'BackpackFreeSlot': 21, 'AmmoMaxStack': 22, 'GunDamage': 23, 'RecoverArmorTime': 24, 'EnergyValueUp': 26, 'ShieldDuration': 27, 'MagicFieldEffectScaleX': 28, 'MagicFieldEffectScaleY': 29, 'MagicFieldEffectScaleZ': 30, 'MissileStrikeCount': 31, 'MissileDamage': 32, 'SatelliteScanTime': 33, 'SatelliteScanRange': 34, 'LightRayTime': 35, 'LightRayDamage': 36, 'LightRayRange': 37, 'SatelliteScanInterval': 38, 'GasTime': 39, 'GasRange': 40, 'GasDamage': 41, 'CureUavCureSpeed': 42, 'FullScanTime': 43, 'GasFiledDamage': 44, 'SkillRange': 45, 'CannonDamage': 46, 'AssassinateEnergyUp': 47, 'UavRecoverArmorSpeed': 48, 'ParanoiaDistance': 49, 'ParanoiaRadius': 50, 'ParanoiaTime': 51, 'ShadowTime': 52, 'ShadowRange': 53, 'MoveDamageReduce': 54, 'ForbidChangeWeapon': 55, 'EnergySkillChargeSpeed': 56, 'SkillChargeSpeed': 57, 'CureValueUp': 58, 'ForbidRestoreHP': 59, 'ForbidRestoreArmor': 60, 'Invincible': 61, 'BanSprint': 62, 'UseCureItemSpeed': 63, 'SkillMaxCount': 64, 'CureUavRangeUp': 65, 'CureUavTimeUp': 66, 'ZombieDamageDown': 67}
    value_to_names = {1: 'MaxHp', 2: 'HelpOtherSpeed', 3: 'MaxArmor', 4: 'Ninja', 5: 'Goggle', 6: 'HeatResist', 7: 'ANTI_RESTORE_HP_TIME', 8: 'SupplyProb', 9: 'TaskReward', 10: 'KillReward', 11: 'RecoverSpeed', 12: 'MaxStack', 13: 'SkillRechargeTime', 14: 'StorePrice', 15: 'BombDamageRange', 16: 'BombDamage', 17: 'BombBuffRange', 18: 'BombBuffDuration', 19: 'RecoverArmorSpeed', 20: 'HelpOtherFinishHp', 21: 'BackpackFreeSlot', 22: 'AmmoMaxStack', 23: 'GunDamage', 24: 'RecoverArmorTime', 26: 'EnergyValueUp', 27: 'ShieldDuration', 28: 'MagicFieldEffectScaleX', 29: 'MagicFieldEffectScaleY', 30: 'MagicFieldEffectScaleZ', 31: 'MissileStrikeCount', 32: 'MissileDamage', 33: 'SatelliteScanTime', 34: 'SatelliteScanRange', 35: 'LightRayTime', 36: 'LightRayDamage', 37: 'LightRayRange', 38: 'SatelliteScanInterval', 39: 'GasTime', 40: 'GasRange', 41: 'GasDamage', 42: 'CureUavCureSpeed', 43: 'FullScanTime', 44: 'GasFiledDamage', 45: 'SkillRange', 46: 'CannonDamage', 47: 'AssassinateEnergyUp', 48: 'UavRecoverArmorSpeed', 49: 'ParanoiaDistance', 50: 'ParanoiaRadius', 51: 'ParanoiaTime', 52: 'ShadowTime', 53: 'ShadowRange', 54: 'MoveDamageReduce', 55: 'ForbidChangeWeapon', 56: 'EnergySkillChargeSpeed', 57: 'SkillChargeSpeed', 58: 'CureValueUp', 59: 'ForbidRestoreHP', 60: 'ForbidRestoreArmor', 61: 'Invincible', 62: 'BanSprint', 63: 'UseCureItemSpeed', 64: 'SkillMaxCount', 65: 'CureUavRangeUp', 66: 'CureUavTimeUp', 67: 'ZombieDamageDown'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class CombatState(enum):
    ALIVE = 0
    DEAD = 2
    DYING = 1
    GHOST = 3
    NONE = 4
    SPIRIT = 5
    name_to_values = {'ALIVE': 0, 'DYING': 1, 'DEAD': 2, 'GHOST': 3, 'NONE': 4, 'SPIRIT': 5}
    value_to_names = {0: 'ALIVE', 1: 'DYING', 2: 'DEAD', 3: 'GHOST', 4: 'NONE', 5: 'SPIRIT'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class CustomListType(area_list):
    IS_CUSTOM_TYPE = True
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>


class CustomMapType(area_map):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class Faction(enum):
    ATTACKER = 150
    CHAOS = -1
    DEFENDER = 151
    name_to_values = {'CHAOS': -1, 'ATTACKER': 150, 'DEFENDER': 151}
    value_to_names = {-1: 'CHAOS', 150: 'ATTACKER', 151: 'DEFENDER'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class IBuffs(CustomMapType):
    CALLBACK = {'add': 'OnAddBuff', 'remove': 'OnRemoveBuff'}
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.ibuff.IBuff'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def AddBuff(self, buff): ...

    def Clear(self): ...

    def GetBuff(self, guid): ...

    def GetBuffsByEffect(self, effect): ...

    def GetBuffsByType(self, kind): ...

    def GetBuffsByTypeFromCategory(self, kind): ...

    def HasBuffsByEffect(self, effect): ...

    def HasBuffsByType(self, kind): ...

    def RemoveBuff(self, guid): ...

    def RemoveBuffsByEffect(self, effect): ...

    def RemoveBuffsByType(self, kind): ...

    def RemoveExpires(self): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class IBuffsShadow(CustomMapType):
    CALLBACK = {'add': 'OnAddBuff', 'remove': 'OnRemoveBuff'}
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.ibuff.IBuffShadow'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def AddBuff(self, buff): ...

    def Clear(self): ...

    def GetBuff(self, guid): ...

    def GetBuffsByEffect(self, effect): ...

    def GetBuffsByType(self, kind): ...

    def GetBuffsByTypeFromCategory(self, kind): ...

    def HasBuffsByEffect(self, effect): ...

    def HasBuffsByType(self, kind): ...

    def RemoveBuff(self, guid): ...

    def RemoveBuffsByEffect(self, effect): ...

    def RemoveBuffsByType(self, kind): ...

    def RemoveExpires(self): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class ICombatAttr(CustomMapType):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def CalResult(self, base_value, attr_name, gun_type=0, equip_id=''): ...

    def CheckAttrBool(self, attr_name, gun_type=0, equip_id=''): ...

    def CheckAttrIsCov(self, attr_name, gun_type=0, equip_id=''): ...

    def DoCalResult(self, base_value, attr_name, gun_type=0, equip_id='', use_shadow=False): ...

    def GetAttrValue(self, attr_name, gun_type=0, equip_id='', use_shadow=False): ...

    def HasAttr(self, attr_name, gun_type=0, equip_id=''): ...

    def OnAdd_BackpackFreeSlot(self, attr): ...

    def OnAdd_MaxArmor(self, attr): ...

    def OnAdd_MaxHp(self, attr): ...

    def OnRemove_BackpackFreeSlot(self, attr): ...

    def OnRemove_MaxArmor(self, attr): ...

    def OnRemove_MaxHp(self, attr): ...

    def OnUpdate_BackpackFreeSlot(self, attr): ...

    def OnUpdate_MaxArmor(self, attr): ...

    def OnUpdate_MaxHp(self, attr): ...

    def OnUpdate_StorePrice(self, attr): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class ICombatUnit(ICombatUnitBase):
    IsATM = False
    IsATMGuardAI = False
    IsAirDrop = False
    IsAltar = False
    IsAmmoBox = False
    IsArrow = False
    IsAttackDrone = False
    IsAvatar = False
    IsBarrieCannon = False
    IsBleachSpirit = False
    IsBomb = False
    IsBuilding = False
    IsChaosUav = False
    IsCombatAvatar = False
    IsCombatAvatarSniper = False
    IsCombatAvatarZombieXray = False
    IsCombatBillboard = False
    IsCombatTeam = False
    IsCombatUnit = True
    IsContrabandPlane = False
    IsContractDesk = False
    IsCrack = False
    IsCrow = False
    IsCureUav = False
    IsCureUavFix = False
    IsCureUavShield = False
    IsDestructible = False
    IsDummyCombatAvatar = False
    IsEmoteTree = False
    IsEnergyStronghold = False
    IsEntityAttach = False
    IsEntityMaster = False
    IsEvaGame = False
    IsEvaMonster = False
    IsEvoPlatform = False
    IsGameLogic = False
    IsGasStation = False
    IsGlass = False
    IsGroupDanceField = False
    IsHelenAI = False
    IsHiderClone = False
    IsHolographicRobot = False
    IsIceWall = False
    IsIgnoreCue = False
    IsItem = False
    IsItemSpaceSnare = False
    IsMagicField = False
    IsMineral = False
    IsMonitorMissile = False
    IsMonster = False
    IsMovingPlatform = False
    IsNavigateBarrieCannon = False
    IsNewCrystalMonster = False
    IsObserveAvatar = False
    IsOccupyContractTarget = False
    IsOccupyContractTargetNew = False
    IsOilbox = False
    IsPhyBall = False
    IsPlayerCombatAvatar = False
    IsPlayerObserveAvatar = False
    IsPortableShop = False
    IsPosterBoard = False
    IsRPGMissile = False
    IsReplayPuppet = False
    IsReplayRecorder = False
    IsRobotCombatAvatar = False
    IsRobotCombatAvatarZombie = False
    IsSafeBox = False
    IsSaveDrone = False
    IsSaveMachine = False
    IsScoutArrow = False
    IsSearchContractBox = False
    IsShield = False
    IsShootingRange = False
    IsShop = False
    IsSimpleCombatUnit = True
    IsSkullBomb = False
    IsSpellDrone = False
    IsStickyMaster = False
    IsStronghold = False
    IsStropUav = False
    IsSupply = False
    IsSwordSpirit = False
    IsSyncTransEntity = False
    IsSystemKiller = False
    IsTransferBomb = False
    IsUavShield = False
    IsVehicle = False
    IsVirtualInteractionEntity = False
    NinjaBeacon = False
    is_fps_avatar = False
    is_replay_avatar = False
    is_replay_room = False

    @property
    def base_armor(self): ...

    @property
    def base_maxarmor(self): ...

    @property
    def cur_maxhp(self): ...

    @property
    def design_combat_properties(self): ...

    @property
    def extra_armor(self): ...

    @property
    def hand_model_id(self): ...

    @property
    def is_alive(self): ...

    @property
    def is_alive_state(self): ...

    @property
    def is_ban_sprint(self): ...

    @property
    def is_dead_state(self): ...

    @property
    def is_dying_state(self): ...

    @property
    def is_invincible(self): ...

    @property
    def unit_model_id(self): ...

    def CalAttrResult(self, attr_type, value, equip_id=''): ...

    def HasAttr(self, attr_type): ...

    def HasBuff(self, guid): ...

    def HasBuffByKind(self, kind): ...

    def HasBuffByKinds(self, kinds): ...

class ICombatUnitBase(ISimpleCombatUnitBase):
    IsATM = False
    IsATMGuardAI = False
    IsAirDrop = False
    IsAltar = False
    IsAmmoBox = False
    IsArrow = False
    IsAttackDrone = False
    IsAvatar = False
    IsBarrieCannon = False
    IsBleachSpirit = False
    IsBomb = False
    IsBuilding = False
    IsChaosUav = False
    IsCombatAvatar = False
    IsCombatAvatarSniper = False
    IsCombatAvatarZombieXray = False
    IsCombatBillboard = False
    IsCombatTeam = False
    IsCombatUnit = True
    IsContrabandPlane = False
    IsContractDesk = False
    IsCrack = False
    IsCrow = False
    IsCureUav = False
    IsCureUavFix = False
    IsCureUavShield = False
    IsDestructible = False
    IsDummyCombatAvatar = False
    IsEmoteTree = False
    IsEnergyStronghold = False
    IsEntityAttach = False
    IsEntityMaster = False
    IsEvaGame = False
    IsEvaMonster = False
    IsEvoPlatform = False
    IsGameLogic = False
    IsGasStation = False
    IsGlass = False
    IsGroupDanceField = False
    IsHelenAI = False
    IsHiderClone = False
    IsHolographicRobot = False
    IsIceWall = False
    IsIgnoreCue = False
    IsItem = False
    IsItemSpaceSnare = False
    IsMagicField = False
    IsMineral = False
    IsMonitorMissile = False
    IsMonster = False
    IsMovingPlatform = False
    IsNavigateBarrieCannon = False
    IsNewCrystalMonster = False
    IsObserveAvatar = False
    IsOccupyContractTarget = False
    IsOccupyContractTargetNew = False
    IsOilbox = False
    IsPhyBall = False
    IsPlayerCombatAvatar = False
    IsPlayerObserveAvatar = False
    IsPortableShop = False
    IsPosterBoard = False
    IsRPGMissile = False
    IsReplayPuppet = False
    IsReplayRecorder = False
    IsRobotCombatAvatar = False
    IsRobotCombatAvatarZombie = False
    IsSafeBox = False
    IsSaveDrone = False
    IsSaveMachine = False
    IsScoutArrow = False
    IsSearchContractBox = False
    IsShield = False
    IsShootingRange = False
    IsShop = False
    IsSimpleCombatUnit = True
    IsSkullBomb = False
    IsSpellDrone = False
    IsStickyMaster = False
    IsStronghold = False
    IsStropUav = False
    IsSupply = False
    IsSwordSpirit = False
    IsSyncTransEntity = False
    IsSystemKiller = False
    IsTransferBomb = False
    IsUavShield = False
    IsVehicle = False
    IsVirtualInteractionEntity = False
    NinjaBeacon = False
    is_fps_avatar = False
    is_replay_avatar = False
    is_replay_room = False

    @property
    def base_armor(self): ...

    @property
    def base_maxarmor(self): ...

    @property
    def cur_maxhp(self): ...

    @property
    def design_combat_properties(self): ...

    @property
    def extra_armor(self): ...

    @property
    def hand_model_id(self): ...

    @property
    def is_alive(self): ...

    @property
    def is_alive_state(self): ...

    @property
    def is_ban_sprint(self): ...

    @property
    def is_dead_state(self): ...

    @property
    def is_dying_state(self): ...

    @property
    def is_invincible(self): ...

    @property
    def unit_model_id(self): ...

    def CalAttrResult(self, attr_type, value, equip_id=''): ...

    def HasAttr(self, attr_type): ...

    def HasBuff(self, guid): ...

    def HasBuffByKind(self, kind): ...

    def HasBuffByKinds(self, kinds): ...

class ISimpleCombatUnit(ISimpleCombatUnitBase):
    IsATM = False
    IsATMGuardAI = False
    IsAirDrop = False
    IsAltar = False
    IsAmmoBox = False
    IsArrow = False
    IsAttackDrone = False
    IsAvatar = False
    IsBarrieCannon = False
    IsBleachSpirit = False
    IsBomb = False
    IsBuilding = False
    IsChaosUav = False
    IsCombatAvatar = False
    IsCombatAvatarSniper = False
    IsCombatAvatarZombieXray = False
    IsCombatBillboard = False
    IsCombatTeam = False
    IsCombatUnit = False
    IsContrabandPlane = False
    IsContractDesk = False
    IsCrack = False
    IsCrow = False
    IsCureUav = False
    IsCureUavFix = False
    IsCureUavShield = False
    IsDestructible = False
    IsDummyCombatAvatar = False
    IsEmoteTree = False
    IsEnergyStronghold = False
    IsEntityAttach = False
    IsEntityMaster = False
    IsEvaGame = False
    IsEvaMonster = False
    IsEvoPlatform = False
    IsGameLogic = False
    IsGasStation = False
    IsGlass = False
    IsGroupDanceField = False
    IsHelenAI = False
    IsHiderClone = False
    IsHolographicRobot = False
    IsIceWall = False
    IsIgnoreCue = False
    IsItem = False
    IsItemSpaceSnare = False
    IsMagicField = False
    IsMineral = False
    IsMonitorMissile = False
    IsMonster = False
    IsMovingPlatform = False
    IsNavigateBarrieCannon = False
    IsNewCrystalMonster = False
    IsObserveAvatar = False
    IsOccupyContractTarget = False
    IsOccupyContractTargetNew = False
    IsOilbox = False
    IsPhyBall = False
    IsPlayerCombatAvatar = False
    IsPlayerObserveAvatar = False
    IsPortableShop = False
    IsPosterBoard = False
    IsRPGMissile = False
    IsReplayPuppet = False
    IsReplayRecorder = False
    IsRobotCombatAvatar = False
    IsRobotCombatAvatarZombie = False
    IsSafeBox = False
    IsSaveDrone = False
    IsSaveMachine = False
    IsScoutArrow = False
    IsSearchContractBox = False
    IsShield = False
    IsShootingRange = False
    IsShop = False
    IsSimpleCombatUnit = True
    IsSkullBomb = False
    IsSpellDrone = False
    IsStickyMaster = False
    IsStronghold = False
    IsStropUav = False
    IsSupply = False
    IsSwordSpirit = False
    IsSyncTransEntity = False
    IsSystemKiller = False
    IsTransferBomb = False
    IsUavShield = False
    IsVehicle = False
    IsVirtualInteractionEntity = False
    NinjaBeacon = False
    is_fps_avatar = False
    is_replay_avatar = False
    is_replay_room = False

    @property
    def is_alive(self): ...

    @property
    def is_invincible(self): ...


class ISimpleCombatUnitBase:
    IsATM = False
    IsATMGuardAI = False
    IsAirDrop = False
    IsAltar = False
    IsAmmoBox = False
    IsArrow = False
    IsAttackDrone = False
    IsAvatar = False
    IsBarrieCannon = False
    IsBleachSpirit = False
    IsBomb = False
    IsBuilding = False
    IsChaosUav = False
    IsCombatAvatar = False
    IsCombatAvatarSniper = False
    IsCombatAvatarZombieXray = False
    IsCombatBillboard = False
    IsCombatTeam = False
    IsCombatUnit = False
    IsContrabandPlane = False
    IsContractDesk = False
    IsCrack = False
    IsCrow = False
    IsCureUav = False
    IsCureUavFix = False
    IsCureUavShield = False
    IsDestructible = False
    IsDummyCombatAvatar = False
    IsEmoteTree = False
    IsEnergyStronghold = False
    IsEntityAttach = False
    IsEntityMaster = False
    IsEvaGame = False
    IsEvaMonster = False
    IsEvoPlatform = False
    IsGameLogic = False
    IsGasStation = False
    IsGlass = False
    IsGroupDanceField = False
    IsHelenAI = False
    IsHiderClone = False
    IsHolographicRobot = False
    IsIceWall = False
    IsIgnoreCue = False
    IsItem = False
    IsItemSpaceSnare = False
    IsMagicField = False
    IsMineral = False
    IsMonitorMissile = False
    IsMonster = False
    IsMovingPlatform = False
    IsNavigateBarrieCannon = False
    IsNewCrystalMonster = False
    IsObserveAvatar = False
    IsOccupyContractTarget = False
    IsOccupyContractTargetNew = False
    IsOilbox = False
    IsPhyBall = False
    IsPlayerCombatAvatar = False
    IsPlayerObserveAvatar = False
    IsPortableShop = False
    IsPosterBoard = False
    IsRPGMissile = False
    IsReplayPuppet = False
    IsReplayRecorder = False
    IsRobotCombatAvatar = False
    IsRobotCombatAvatarZombie = False
    IsSafeBox = False
    IsSaveDrone = False
    IsSaveMachine = False
    IsScoutArrow = False
    IsSearchContractBox = False
    IsShield = False
    IsShootingRange = False
    IsShop = False
    IsSimpleCombatUnit = True
    IsSkullBomb = False
    IsSpellDrone = False
    IsStickyMaster = False
    IsStronghold = False
    IsStropUav = False
    IsSupply = False
    IsSwordSpirit = False
    IsSyncTransEntity = False
    IsSystemKiller = False
    IsTransferBomb = False
    IsUavShield = False
    IsVehicle = False
    IsVirtualInteractionEntity = False
    NinjaBeacon = False
    is_fps_avatar = False
    is_replay_avatar = False
    is_replay_room = False

    @property
    def is_alive(self): ...

    @property
    def is_invincible(self): ...


class PivotalEntityInfo(CustomMapType):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def Clear(self): ...

    def Reset(self, entity): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class PropertyMetaClass(type):
    mro = <method 'mro' of 'type' objects>



# Functions
def Property(name, default, flag=2): ...
def with_tag(*args): ...

