"""
Module: gshare.icredit
Dumped: 2025-12-16T22:16:58.470245
Generated by SDK Dumper
"""

# module: gshare.icredit

# Imports
import gshare.consts

# Variables
COMPONENT = 'Client'
CreditScoreRecordExpiredTime = 7776000
CreditScoreRecordMaxCount = 50
WeekRewardItemList = [(4000000010, 500)]

# Classes
class CreditScoreChangeReason(enum):
    Abuse = 1
    Default = 0
    EarlyExit = 3
    FinishBattle = 4
    Hangup = 2
    NegativeGame = 5
    name_to_values = {'Default': 0, 'Abuse': 1, 'Hangup': 2, 'EarlyExit': 3, 'FinishBattle': 4, 'NegativeGame': 5}
    value_to_names = {0: 'Default', 1: 'Abuse', 2: 'Hangup', 3: 'EarlyExit', 4: 'FinishBattle', 5: 'NegativeGame'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class CustomListType(area_list):
    IS_CUSTOM_TYPE = True
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>


class CustomMapType(area_map):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class ICreditScoreRecord(CustomMapType):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class ICreditScoreRecords(CustomListType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.icredit.ICreditScoreRecord'>
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>


class WeekRewardState(enum):
    CanReceive = 1
    Default = 0
    Received = 2
    name_to_values = {'Default': 0, 'CanReceive': 1, 'Received': 2}
    value_to_names = {0: 'Default', 1: 'CanReceive', 2: 'Received'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class enum:
    name_to_values = {}
    value_to_names = {}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...


# Functions
def GetRequireCreditScore(match_type, match_mode): ...
def Property(name, default, flag=2): ...

