"""
Module: gshare.idaily_special_shop
Dumped: 2025-12-16T22:16:58.474147
Generated by SDK Dumper
"""

# module: gshare.idaily_special_shop

# Imports
import gclient.data.activity_data
import gclient.data.daily_special_data
import gclient.data.daily_special_discount_data
import gclient.data.daily_special_item_data
import gclient.data.daily_special_target_data
import gshare.formula
import gclient.data.lobby_item_data
import gclient.data.pass_season_data
import random
import six2
import time
import gshare.time_util

# Variables
COMPONENT = 'Client'
flags = 10

# Classes
class BpConfig:
    CheapCertification = 1
    FreeCertification = 0
    LuxCertification = 3
    SpCertifications = (1, 2)
    VipCertification = 2

    def GetBpEffectId(bp_type): ...

    def GetBpFreeMaxLevel(act_id): ...

    def GetBpFreeRewardMaxLevel(act_id): ...

    def GetBpLevelScore(act_id, level=1): ...

    def GetBpLuxLevel(act_id): ...

    def GetBpPackageLevel(act_id): ...

    def GetBpWeekCount(act_id): ...

    def GetLevelAndScoreLeftByScore(act_id, bp_score): ...

    def GetScoreLevelUpRequire(act_id, cur_level, level): ...

    def GetWeekTaskConf(act_id): ...

class CustomMapType(area_map):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class IDailySpecialshop(CustomMapType):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def InitShopData(self, set_id, target_id, item_dict, avatar): ...

    def RefreshShopData(self, item_dict, avatar): ...

    def StoreDirectProduct(self, avatar): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class IdManager:
    def bytes2id(bytes): ...

    def genid(): ...

    def id2bytes(uid): ...

    def id2str(uid): ...

    def is_valid_id(entityid): ...

    def str2id(string): ...

class ItemInfo(CustomMapType):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    @property
    def cost_count(self): ...

    @property
    def cost_item_id(self): ...

    @property
    def direct_pkg_id(self): ...

    @property
    def discount(self): ...

    @property
    def discount_cost_count(self): ...

    @property
    def is_direct_product(self): ...

    @property
    def item_count(self): ...

    @property
    def item_id(self): ...

    @property
    def item_proto(self): ...

    @property
    def no_cycle(self): ...

    @property
    def proto(self): ...

    def SetIsBought(self): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class ItemInfoDict(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.idaily_special_shop.ItemInfo'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class partial:
    args = <member 'args' of 'functools.partial' objects>
    func = <member 'func' of 'functools.partial' objects>
    keywords = <member 'keywords' of 'functools.partial' objects>



# Functions
def GetCurNormalBpActId(avatar): ...
def IsAvatarHasItem(avatar, item_id, include_experience_item=False, include_upgrade_item=False): ...
def IsTimeLimitCard(item_id): ...
def Property(name, default, flag=2): ...
def SpecialCheck_BpUpgrade(avatar, item_id): ...

