"""
Module: gshare.imail
Dumped: 2025-12-16T22:16:58.533263
Generated by SDK Dumper
"""

# module: gshare.imail

# Imports
import base64
import pickle
import json
import gclient.data.mail_format_data
import gclient.util.mail_language_util
import gclient.data.mail_multi_data
import six2
import sys

# Variables
ACTIVATE_CODE_FACEBOOK = 1
ACTIVATE_CODE_QUESTIONNAIRE = 2
COMPONENT = 'Client'
TAB_BATTLE = 3
TAB_REWARD = 2
TAB_SYS = 1

# Classes
class CustomMapType(area_map):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class IMail(CustomMapType):
    IS_CUSTOM_TYPE = True
    ITEM_SEP_ATTR = '*'
    ITEM_SEP_PAIR = ';'
    ITEM_SOURCE = 'item_source'
    KEY_ACTIVATED = 'activated'
    KEY_ASK_INFO = 'ask'
    KEY_ASK_PRESENT_ITEM = 'ask_present_item'
    KEY_BATTLE_HELP = 'from_avatarid'
    KEY_BUTTON = 'button'
    KEY_CLAN_SENDER = 'clan_sender'
    KEY_EXPIRED_TIME = 'expired_time'
    KEY_FORMAT = 'format_id'
    KEY_GIFT_INFO = 'gift'
    KEY_ITEMS = 'items'
    KEY_ITEMS_EXTRA = 'items_extra'
    KEY_ITEM_EXPIRE_TIME = 'item_expire_time'
    KEY_ITEM_HAS_GET = 'has_get'
    KEY_LINKS = 'links'
    KEY_MALL_ASK_INFO = 'mall_ask'
    KEY_MALL_GIFT_HAS_SEND = 'has_send_gift'
    KEY_MALL_GIFT_INFO = 'mall_gift'
    KEY_MULTI_MAIL_ARGS = 'args'
    KEY_MULTI_MAIL_ID = 'multi_mail_id'
    KEY_PLUGIN_REPORT = 'rerole_id'
    KEY_PRESENT_ITEM = 'present_item'
    KEY_TAB = 'tab'
    KEY_THANK_INFO = 'thank'
    KEY_URL = 'url'
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    @property
    def is_activated(self): ...

    @property
    def item_str(self): ...

    @property
    def mail_proto(self): ...

    @property
    def multi_mail_args(self): ...

    @property
    def multi_mail_id(self): ...

    @property
    def tab(self): ...

    def Activate(self): ...

    def Consumed(self): ...

    def Expired(self, now): ...

    def GetItems(self): ...

    def HasItems(self): ...

    def IsRead(self): ...

    def MarkRead(self): ...

    def RefillBody(self, country_code='zh'): ...

    def SetConsumed(self): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class MailStatus(enum):
    Read = 1
    Unread = 0
    name_to_values = {'Unread': 0, 'Read': 1}
    value_to_names = {0: 'Unread', 1: 'Read'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class Mails(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.imail.IMail'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class PropertyMetaClass(type):
    mro = <method 'mro' of 'type' objects>



# Functions
def Property(name, default, flag=2): ...

