"""
Module: gshare.irace_mail
Dumped: 2025-12-16T22:16:58.578942
Generated by SDK Dumper
"""

# module: gshare.irace_mail

# Imports
import base64
import pickle
import json
import gclient.util.mail_language_util
import gclient.data.race_mail_data
import six2
import sys
import gshare.time_util

# Variables
COMPONENT = 'Client'

# Classes
class CustomMapType(area_map):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class IRaceMail(CustomMapType):
    IS_CUSTOM_TYPE = True
    ITEM_SEP_ATTR = '*'
    ITEM_SEP_PAIR = ';'
    ITEM_SOURCE = 'item_source'
    KEY_EXPIRED_TIME = 'expired_time'
    KEY_ITEMS = 'items'
    KEY_ITEMS_EXTRA = 'items_extra'
    KEY_ITEM_HAS_GET = 'has_get'
    KEY_MULTI_MAIL_ARGS = 'args'
    KEY_MULTI_MAIL_ID = 'race_mail_id'
    KEY_RACE_ID = 'race_id'
    KEY_RACE_TEAM_ID = 'race_team_id'
    KEY_TAB = 'tab'
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    @property
    def item_str(self): ...

    @property
    def mail_proto(self): ...

    @property
    def multi_mail_args(self): ...

    @property
    def race_id(self): ...

    @property
    def race_team_id(self): ...

    @property
    def tab(self): ...

    def Consumed(self): ...

    def Expired(self, now): ...

    def GetItems(self): ...

    def HasItems(self): ...

    def IsRead(self): ...

    def MarkRead(self): ...

    def RefillBody(self, country_code='zh'): ...

    def SetConsumed(self): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class MailStatus(enum):
    Read = 1
    Unread = 0
    name_to_values = {'Unread': 0, 'Read': 1}
    value_to_names = {0: 'Unread', 1: 'Read'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class PropertyMetaClass(type):
    mro = <method 'mro' of 'type' objects>


class RaceMailTab(enum):
    TAB_RACE = 1
    TAB_TEAM = 2
    name_to_values = {'TAB_RACE': 1, 'TAB_TEAM': 2}
    value_to_names = {1: 'TAB_RACE', 2: 'TAB_TEAM'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class RaceMailType(enum):
    CANCEL_APPLY = 8
    CTRATE_RACE_CANCEL = 7
    JOIN_RACE_ALREADY_START = 5
    JOIN_RACE_APPLY = 1
    JOIN_RACE_APPLY_SEND = 2
    JOIN_RACE_CANCEL_FAIL = 6
    JOIN_RACE_KICKED = 3
    JOIN_RACE_LOCKED = 4
    RACE_APPLY_REFUSE = 10
    RACE_INTERRUPT = 9
    RACE_REPAIR = 11
    RACE_REPAIR_NOTICE = 12
    RACE_TIME_CHANGE = 13
    TEAM_JOIN_RACE_SUCCESS = 21
    TEAM_MEMBER_APPLY = 24
    TEAM_MEMBER_LEAVE = 23
    TEAM_NEW_MEMBER = 22
    TEAM_RACE_ACE_PRIZE = 26
    TEAM_RACE_PRIZE = 25
    name_to_values = {'JOIN_RACE_APPLY': 1, 'JOIN_RACE_APPLY_SEND': 2, 'JOIN_RACE_KICKED': 3, 'JOIN_RACE_LOCKED': 4, 'JOIN_RACE_ALREADY_START': 5, 'JOIN_RACE_CANCEL_FAIL': 6, 'CTRATE_RACE_CANCEL': 7, 'CANCEL_APPLY': 8, 'RACE_INTERRUPT': 9, 'RACE_APPLY_REFUSE': 10, 'RACE_REPAIR': 11, 'RACE_REPAIR_NOTICE': 12, 'RACE_TIME_CHANGE': 13, 'TEAM_JOIN_RACE_SUCCESS': 21, 'TEAM_NEW_MEMBER': 22, 'TEAM_MEMBER_LEAVE': 23, 'TEAM_MEMBER_APPLY': 24, 'TEAM_RACE_PRIZE': 25, 'TEAM_RACE_ACE_PRIZE': 26}
    value_to_names = {1: 'JOIN_RACE_APPLY', 2: 'JOIN_RACE_APPLY_SEND', 3: 'JOIN_RACE_KICKED', 4: 'JOIN_RACE_LOCKED', 5: 'JOIN_RACE_ALREADY_START', 6: 'JOIN_RACE_CANCEL_FAIL', 7: 'CTRATE_RACE_CANCEL', 8: 'CANCEL_APPLY', 9: 'RACE_INTERRUPT', 10: 'RACE_APPLY_REFUSE', 11: 'RACE_REPAIR', 12: 'RACE_REPAIR_NOTICE', 13: 'RACE_TIME_CHANGE', 21: 'TEAM_JOIN_RACE_SUCCESS', 22: 'TEAM_NEW_MEMBER', 23: 'TEAM_MEMBER_LEAVE', 24: 'TEAM_MEMBER_APPLY', 25: 'TEAM_RACE_PRIZE', 26: 'TEAM_RACE_ACE_PRIZE'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class RaceMails(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.irace_mail.IRaceMail'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class enum:
    name_to_values = {}
    value_to_names = {}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...


# Functions
def Property(name, default, flag=2): ...

