"""
Module: gshare.irank
Dumped: 2025-12-16T22:16:58.582845
Generated by SDK Dumper
"""

# module: gshare.irank

# Imports
import gclient.data.rank_data
import time

# Variables
CLIENT_ONLY = 1
COMPONENT = 'Client'
RankPlayerInfoKey = ['id', 'score', 'show_name', 'extra', 'ranking', 'official_head', 'gender', 'head_url', 'legend_rank_dict', 'head_frame', 'card_background', 'national_flag', 'clan_name', 'clan_icon']
SERVER_ONLY = 4
_reload_all = True

# Classes
class CustomListListType(CustomListType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'common.classutils.CustomListType'>
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>


class CustomListType(area_list):
    IS_CUSTOM_TYPE = True
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>


class CustomMapType(area_map):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class RankKey(enum):
    GrandTheft = 13
    GrandTheftActivity = 17
    GrandTheftDaily = 14
    GrandTheftTopCoin = 15
    HumanKillZombie = 23
    HumanKillZombieWeek = 22
    Kill = 3
    Peak = 18
    Qualifying = 1
    ShootingChallenge = 1000
    ShutterIslandEnergy = 8
    SquadFightKill = 6
    SquadFightQualifying = 5
    ZombieKillHuman = 21
    ZombieKillHumanWeek = 20
    ZombieWin = 16
    name_to_values = {'Qualifying': 1, 'Kill': 3, 'SquadFightQualifying': 5, 'SquadFightKill': 6, 'ShutterIslandEnergy': 8, 'GrandTheftActivity': 17, 'GrandTheft': 13, 'GrandTheftDaily': 14, 'GrandTheftTopCoin': 15, 'ZombieWin': 16, 'Peak': 18, 'ZombieKillHumanWeek': 20, 'ZombieKillHuman': 21, 'HumanKillZombieWeek': 22, 'HumanKillZombie': 23, 'ShootingChallenge': 1000}
    value_to_names = {1: 'Qualifying', 3: 'Kill', 5: 'SquadFightQualifying', 6: 'SquadFightKill', 8: 'ShutterIslandEnergy', 17: 'GrandTheftActivity', 13: 'GrandTheft', 14: 'GrandTheftDaily', 15: 'GrandTheftTopCoin', 16: 'ZombieWin', 18: 'Peak', 20: 'ZombieKillHumanWeek', 21: 'ZombieKillHuman', 22: 'HumanKillZombieWeek', 23: 'HumanKillZombie', 1000: 'ShootingChallenge'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class RankScoreUnit(CustomMapType):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    @property
    def score(self): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class RankScores(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.irank.RankScoreUnit'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def GetScore(self, rank_key): ...

    def SetScore(self, rank_key, score): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class RankServerFriend(enum):
    Friend = 2
    Server = 1
    name_to_values = {'Server': 1, 'Friend': 2}
    value_to_names = {1: 'Server', 2: 'Friend'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class RankWindowRankKey(enum):
    HumanKillZombie = 23
    HumanKillZombieWeek = 22
    Kill = 3
    Qualifying = 1
    SquadFightKill = 6
    SquadFightQualifying = 5
    ZombieKillHuman = 21
    ZombieKillHumanWeek = 20
    name_to_values = {'Qualifying': 1, 'Kill': 3, 'SquadFightQualifying': 5, 'SquadFightKill': 6, 'ZombieKillHumanWeek': 20, 'ZombieKillHuman': 21, 'HumanKillZombieWeek': 22, 'HumanKillZombie': 23}
    value_to_names = {1: 'Qualifying', 3: 'Kill', 5: 'SquadFightQualifying', 6: 'SquadFightKill', 20: 'ZombieKillHumanWeek', 21: 'ZombieKillHuman', 22: 'HumanKillZombieWeek', 23: 'HumanKillZombie'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class RankingMode(enum):
    Figure = 1
    FigureAndPercent = 3
    Percent = 2
    name_to_values = {'Figure': 1, 'Percent': 2, 'FigureAndPercent': 3}
    value_to_names = {1: 'Figure', 2: 'Percent', 3: 'FigureAndPercent'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class RankingRefreshType(enum):
    Daily = 1
    Monthly = 3
    NoRefresh = 0
    Seasonly = 4
    Seasonly_1004 = 1004
    Seasonly_1300 = 1300
    Weekly = 2
    name_to_values = {'NoRefresh': 0, 'Daily': 1, 'Weekly': 2, 'Monthly': 3, 'Seasonly': 4, 'Seasonly_1004': 1004, 'Seasonly_1300': 1300}
    value_to_names = {0: 'NoRefresh', 1: 'Daily', 2: 'Weekly', 3: 'Monthly', 4: 'Seasonly', 1004: 'Seasonly_1004', 1300: 'Seasonly_1300'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class RankingSettleType(RankingRefreshType):
    Daily = 1
    Expired = 5
    Monthly = 3
    NoRefresh = 0
    Seasonly = 4
    Seasonly_1004 = 1004
    Seasonly_1300 = 1300
    Weekly = 2
    name_to_values = {'Expired': 5}
    value_to_names = {5: 'Expired'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class RankingType(enum):
    Avatar = 1
    Zone = 2
    name_to_values = {'Avatar': 1, 'Zone': 2}
    value_to_names = {1: 'Avatar', 2: 'Zone'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class enum:
    name_to_values = {}
    value_to_names = {}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...


# Functions
def ExtraProperty(name, default): ...
def IsReverse(rank_key): ...
def Property(name, default, flag=2): ...
def rpc_method(rpctype, *types): ...

