"""
Module: gshare.irecruit
Dumped: 2025-12-16T22:16:58.601379
Generated by SDK Dumper
"""

# module: gshare.irecruit

# Imports
import gshare.consts
import gclient.data.match_client_data
import gclient.data.rank_level_data
import gclient.data.space_data
import time
import gshare.time_util

# Variables
COMPONENT = 'Client'
DEFAULT_MATCH_TYPE = 1004
HALF_DIV_RANGE = 2
PROTECT_TIME = 3
TIMEOUT = 300

# Classes
class CrossPlatform(enum):
    Off = 0
    On = 1
    name_to_values = {'Off': 0, 'On': 1}
    value_to_names = {0: 'Off', 1: 'On'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class CustomMapType(area_map):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class DeviceType(enum):
    Mobile = 1
    PC = 2
    name_to_values = {'Mobile': 1, 'PC': 2}
    value_to_names = {1: 'Mobile', 2: 'PC'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class IdManager:
    def bytes2id(bytes): ...

    def genid(): ...

    def id2bytes(uid): ...

    def id2str(uid): ...

    def is_valid_id(entityid): ...

    def str2id(string): ...

class MatchMode(enum):
    FIVE = 5
    FOUR = 4
    MULTI = 2
    SINGLE = 1
    SIX = 6
    THREE = 3
    name_to_values = {'SINGLE': 1, 'MULTI': 2, 'THREE': 3, 'FOUR': 4, 'FIVE': 5, 'SIX': 6}
    value_to_names = {1: 'SINGLE', 2: 'MULTI', 3: 'THREE', 4: 'FOUR', 5: 'FIVE', 6: 'SIX'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class MatchWay(enum):
    Normal = 2
    Rank = 1
    name_to_values = {'Rank': 1, 'Normal': 2}
    value_to_names = {1: 'Rank', 2: 'Normal'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class Mic(enum):
    Off = 0
    On = 1
    name_to_values = {'Off': 0, 'On': 1}
    value_to_names = {0: 'Off', 1: 'On'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class RecruitTeam:
    @property
    def destroyed(self): ...

    @property
    def is_expired(self): ...

    @property
    def updated(self): ...

    def CanJoin(self, avatar): ...

    def Pack(self): ...

    def Update(self, info): ...

class enum:
    name_to_values = {}
    value_to_names = {}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...


# Functions
def CanClientRemoveTeam(server_pack_info, team): ...
def GSharePrompt(proto_id, extra_data=None, extra_info=None): ...
def Property(name, default, flag=2): ...
def get_rank_class(qualifying_match_type, qualifying_level): ...
def get_rank_class_range(qualifying_match_type, qualifying_level): ...

