"""
Module: gshare.iroom
Dumped: 2025-12-16T22:16:58.629683
Generated by SDK Dumper
"""

# module: gshare.iroom

# Imports
import gshare.consts
import hashlib
import gshare.irace
import gclient.data.match_data
import gclient.data.room_data
import six2
import gclient.data.space_data

# Variables
COMPONENT = 'Client'
MAX_WATCHER_COUNT = 30
WATCHER_SLOT_OFFSET = 10000

# Classes
class CustomListType(area_list):
    IS_CUSTOM_TYPE = True
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>


class CustomMapType(area_map):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class DeviceType(enum):
    Mobile = 1
    PC = 2
    name_to_values = {'Mobile': 1, 'PC': 2}
    value_to_names = {1: 'Mobile', 2: 'PC'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class IRoom(CustomMapType):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    @property
    def battle_count(self): ...

    @property
    def need_password(self): ...

    @property
    def team_count(self): ...

    @property
    def watcher_count(self): ...

    def CanChangeOption(self, options): ...

    def CanKickout(self, owner_id, target_id): ...

    def CanMatch(self, avatar_id): ...

    def GetMember(self, avatar_id): ...

    def GetMemberBySlot(self, slot): ...

    def GetMemberRoomSlot(self, avatar_id): ...

    def IsGameMember(self, avatarid): ...

    def IsInRoom(self, avatarid): ...

    def IsRoomOwner(self, avatarid): ...

    def IsRoomWatcher(self, avatarid): ...

    def IsValidSlot(self, slot): ...

    def IsWaitingState(self): ...

    def Pack(self): ...

    def PackCommon(self): ...

    def PackMetaInfo(self): ...

    def UpdteOptions(self, options): ...

    def ZipPack(self, exclude_member_dict=False): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class IRoomMember(PlayerFrame):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    @property
    def is_battler(self): ...

    @property
    def is_watcher(self): ...

    def HasDlc(self, spaceno, match_type): ...

    def HasMap(self, spaceno): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class IRoomMembers(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.iroom.IRoomMember'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class JoinRoomCode(enum):
    Destroy = 5
    Full = 1
    Gaming = 3
    InRoom = 4
    Password = 2
    Success = 0
    name_to_values = {'Success': 0, 'Full': 1, 'Password': 2, 'Gaming': 3, 'InRoom': 4, 'Destroy': 5}
    value_to_names = {0: 'Success', 1: 'Full', 2: 'Password', 3: 'Gaming', 4: 'InRoom', 5: 'Destroy'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class NoPersistentTitles(CustomListType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.ititle.NoPersistentTitle'>
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>


class OptionKey(enum):
    AirdropGauntlet = 'airdrop_gauntlet'
    AirdropStore = 'airdrop_store'
    AirdropSword = 'airdrop_sword'
    Airdrops = 'airdrop'
    AssistAim = 'assist_aim'
    AutoReborn = 'relive'
    BattleTime = 'time'
    CanBuyTacticalLevel = 'can_buy_tactical_level'
    CircleAirline = 'circle_airline'
    Coins = 'coins_range'
    DamageTeammate = 'damage_teammate'
    DisableBot = 'disable_bot'
    DisableSkill = 'disable_skill'
    DropCrystal = 'drop_crystal'
    EVOChargeSpeedRatio = 'evo_charge_speed_ratio'
    EnableEvo = 'enable_evo'
    EvaMonsterSpawn = 'eva_monster_spawn'
    ForbidAssistAim = 'forbid_assist_aim'
    HS_ONLY = 'hs_only'
    InfAmmo = 'infinite_ammo'
    InitTacticalLevel = 'tactical_level'
    JurenAirdropMore = 'juren_airdrop_more'
    JurenSKillNoCd = 'juren_skill_no_cd'
    LeaderMode = 'leader_mode'
    MaxArmor = 'maxarmor'
    MaxHp = 'max_hp'
    NextTime = 'race_begin'
    NoDeathTactical = 'disable_death_tactical_energy'
    OneShotKillChance = 'one_shot_kill_chance'
    PutInVehicle = 'vehicle'
    RaceDelayBegin = 'delay_begin'
    RaceManualStart = 'manual_start'
    RaceRounds = 'race_rounds'
    ReduceSkillCharge = 'reduce_skill_charge'
    RoundToWin = 'round_to_win'
    Rounds = 'round_range'
    SafeRegionDamage = 'safe_region_damage'
    SafeRegionSpeed = 'safe_region_speed'
    SameHero = 'same_hero'
    Score = 'score'
    TaskCount = 'task_count'
    TaskType = 'task_type'
    WeatherType = 'weather'
    ZombieBuyback = 'zombie_buyback'
    ZombieHp = 'zombie_hp'
    ZombieRebornItem = 'zombie_reborn_item'
    ZombieRevive = 'zombie_revive'
    name_to_values = {'MaxHp': 'max_hp', 'MaxArmor': 'maxarmor', 'DamageTeammate': 'damage_teammate', 'InfAmmo': 'infinite_ammo', 'DisableSkill': 'disable_skill', 'ForbidAssistAim': 'forbid_assist_aim', 'Rounds': 'round_range', 'LeaderMode': 'leader_mode', 'RoundToWin': 'round_to_win', 'Coins': 'coins_range', 'InitTacticalLevel': 'tactical_level', 'CanBuyTacticalLevel': 'can_buy_tactical_level', 'AutoReborn': 'relive', 'WeatherType': 'weather', 'PutInVehicle': 'vehicle', 'SafeRegionSpeed': 'safe_region_speed', 'SafeRegionDamage': 'safe_region_damage', 'Airdrops': 'airdrop', 'TaskCount': 'task_count', 'TaskType': 'task_type', 'AirdropStore': 'airdrop_store', 'AssistAim': 'assist_aim', 'DisableBot': 'disable_bot', 'NoDeathTactical': 'disable_death_tactical_energy', 'Score': 'score', 'BattleTime': 'time', 'AirdropSword': 'airdrop_sword', 'AirdropGauntlet': 'airdrop_gauntlet', 'ZombieRevive': 'zombie_revive', 'ZombieHp': 'zombie_hp', 'ZombieRebornItem': 'zombie_reborn_item', 'ZombieBuyback': 'zombie_buyback', 'HS_ONLY': 'hs_only', 'EnableEvo': 'enable_evo', 'EVOChargeSpeedRatio': 'evo_charge_speed_ratio', 'JurenSKillNoCd': 'juren_skill_no_cd', 'JurenAirdropMore': 'juren_airdrop_more', 'SameHero': 'same_hero', 'ReduceSkillCharge': 'reduce_skill_charge', 'CircleAirline': 'circle_airline', 'RaceManualStart': 'manual_start', 'RaceDelayBegin': 'delay_begin', 'RaceRounds': 'race_rounds', 'NextTime': 'race_begin', 'EvaMonsterSpawn': 'eva_monster_spawn', 'OneShotKillChance': 'one_shot_kill_chance', 'DropCrystal': 'drop_crystal'}
    value_to_names = {'max_hp': 'MaxHp', 'maxarmor': 'MaxArmor', 'damage_teammate': 'DamageTeammate', 'infinite_ammo': 'InfAmmo', 'disable_skill': 'DisableSkill', 'forbid_assist_aim': 'ForbidAssistAim', 'round_range': 'Rounds', 'leader_mode': 'LeaderMode', 'round_to_win': 'RoundToWin', 'coins_range': 'Coins', 'tactical_level': 'InitTacticalLevel', 'can_buy_tactical_level': 'CanBuyTacticalLevel', 'relive': 'AutoReborn', 'weather': 'WeatherType', 'vehicle': 'PutInVehicle', 'safe_region_speed': 'SafeRegionSpeed', 'safe_region_damage': 'SafeRegionDamage', 'airdrop': 'Airdrops', 'task_count': 'TaskCount', 'task_type': 'TaskType', 'airdrop_store': 'AirdropStore', 'assist_aim': 'AssistAim', 'disable_bot': 'DisableBot', 'disable_death_tactical_energy': 'NoDeathTactical', 'score': 'Score', 'time': 'BattleTime', 'airdrop_sword': 'AirdropSword', 'airdrop_gauntlet': 'AirdropGauntlet', 'zombie_revive': 'ZombieRevive', 'zombie_hp': 'ZombieHp', 'zombie_reborn_item': 'ZombieRebornItem', 'zombie_buyback': 'ZombieBuyback', 'hs_only': 'HS_ONLY', 'enable_evo': 'EnableEvo', 'evo_charge_speed_ratio': 'EVOChargeSpeedRatio', 'juren_skill_no_cd': 'JurenSKillNoCd', 'juren_airdrop_more': 'JurenAirdropMore', 'same_hero': 'SameHero', 'reduce_skill_charge': 'ReduceSkillCharge', 'circle_airline': 'CircleAirline', 'manual_start': 'RaceManualStart', 'delay_begin': 'RaceDelayBegin', 'race_rounds': 'RaceRounds', 'race_begin': 'NextTime', 'eva_monster_spawn': 'EvaMonsterSpawn', 'one_shot_kill_chance': 'OneShotKillChance', 'drop_crystal': 'DropCrystal'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class OptionType(enum):
    Hard = 2
    Normal = 1
    Relaxed = 3
    UserDefine = 4
    name_to_values = {'Normal': 1, 'Hard': 2, 'Relaxed': 3, 'UserDefine': 4}
    value_to_names = {1: 'Normal', 2: 'Hard', 3: 'Relaxed', 4: 'UserDefine'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class PlayerFrame(CustomMapType):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class RoomDeviceType(enum):
    Mobile = 1
    PC = 2
    name_to_values = {'Mobile': 1, 'PC': 2}
    value_to_names = {1: 'Mobile', 2: 'PC'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class RoomStatus(enum):
    Gaming = 2
    Waiting = 1
    name_to_values = {'Waiting': 1, 'Gaming': 2}
    value_to_names = {1: 'Waiting', 2: 'Gaming'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class enum:
    name_to_values = {}
    value_to_names = {}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...


# Functions
def CheckCobmatDlc(has_dlc_maps_list, has_dlc_matchs_list, spaceno=None, hall_match_type=None): ...
def GetMd5(password): ...
def GetOptionsByType(match_type, option_type): ...
def IsBattleSlot(slot): ...
def Property(name, default, flag=2): ...

