"""
Module: gshare.isetting
Dumped: 2025-12-16T22:16:58.638467
Generated by SDK Dumper
"""

# module: gshare.isetting

# Imports
import six2

# Variables
CurrentServerNum = 4
SETTING_TAG_SA_LOG = {32, 7, 8, 9, 10, 11, 12, 21, 22, 27, 28, 29, 30, 31}
ServerSetting = {1: {'gun_selected_record', 'assistaim_config_mode'}, 2: {'airdrop_setting_publish'}, 24: {'recruit_invite_forbid'}}

# Classes
class CustomMapType(area_map):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class CustomStrMapType(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'str'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class Flags(enum):
    AnchorTitle = 5
    BanVoice = 3
    BigHeadNoBot = 4
    IslandEnergyMode = 2
    SandRecord = 1
    name_to_values = {'SandRecord': 1, 'IslandEnergyMode': 2, 'BanVoice': 3, 'BigHeadNoBot': 4, 'AnchorTitle': 5}
    value_to_names = {1: 'SandRecord', 2: 'IslandEnergyMode', 3: 'BanVoice', 4: 'BigHeadNoBot', 5: 'AnchorTitle'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class ISetting(CustomMapType):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class SettingTag(enum):
    AccountWindow = 24
    BasicWindow = 1
    CloudConfigVersion = 34
    ControlWindow = 3
    ControlWindowController = 44
    ControlWindowPC = 43
    CustomGraphics = 33
    CustomLayoutHelicopterV1Plan0 = 37
    CustomLayoutHelicopterV1Plan1 = 38
    CustomLayoutHelicopterV1Plan2 = 39
    CustomLayoutHelicopterV1Window = 35
    CustomLayoutHelicopterV2Plan0 = 40
    CustomLayoutHelicopterV2Plan1 = 41
    CustomLayoutHelicopterV2Plan2 = 42
    CustomLayoutHelicopterV2Window = 36
    CustomLayoutV1Plan0 = 7
    CustomLayoutV1Plan1 = 8
    CustomLayoutV1Plan2 = 9
    CustomLayoutV1Window = 5
    CustomLayoutV2Plan0 = 10
    CustomLayoutV2Plan1 = 11
    CustomLayoutV2Plan2 = 12
    CustomLayoutV2Window = 6
    CustomLayoutVehicleV1Plan0 = 15
    CustomLayoutVehicleV1Plan1 = 16
    CustomLayoutVehicleV1Plan2 = 17
    CustomLayoutVehicleV1Window = 13
    CustomLayoutVehicleV2Plan0 = 18
    CustomLayoutVehicleV2Plan1 = 19
    CustomLayoutVehicleV2Plan2 = 20
    CustomLayoutVehicleV2Window = 14
    GamePlayWindow = 2
    HotSpotCustomLayoutV1Plan0 = 27
    HotSpotCustomLayoutV1Plan1 = 28
    HotSpotCustomLayoutV1Plan2 = 29
    HotSpotCustomLayoutV1Window = 25
    HotSpotCustomLayoutV2Plan0 = 30
    HotSpotCustomLayoutV2Plan1 = 31
    HotSpotCustomLayoutV2Plan2 = 32
    HotSpotCustomLayoutV2Window = 26
    SensitivityPlan1 = 21
    SensitivityPlan2 = 22
    SensitivityWindow = 23
    name_to_values = {'BasicWindow': 1, 'GamePlayWindow': 2, 'ControlWindow': 3, 'CustomLayoutV1Window': 5, 'CustomLayoutV2Window': 6, 'CustomLayoutV1Plan0': 7, 'CustomLayoutV1Plan1': 8, 'CustomLayoutV1Plan2': 9, 'CustomLayoutV2Plan0': 10, 'CustomLayoutV2Plan1': 11, 'CustomLayoutV2Plan2': 12, 'CustomLayoutVehicleV1Window': 13, 'CustomLayoutVehicleV2Window': 14, 'CustomLayoutVehicleV1Plan0': 15, 'CustomLayoutVehicleV1Plan1': 16, 'CustomLayoutVehicleV1Plan2': 17, 'CustomLayoutVehicleV2Plan0': 18, 'CustomLayoutVehicleV2Plan1': 19, 'CustomLayoutVehicleV2Plan2': 20, 'SensitivityPlan1': 21, 'SensitivityPlan2': 22, 'SensitivityWindow': 23, 'AccountWindow': 24, 'HotSpotCustomLayoutV1Window': 25, 'HotSpotCustomLayoutV2Window': 26, 'HotSpotCustomLayoutV1Plan0': 27, 'HotSpotCustomLayoutV1Plan1': 28, 'HotSpotCustomLayoutV1Plan2': 29, 'HotSpotCustomLayoutV2Plan0': 30, 'HotSpotCustomLayoutV2Plan1': 31, 'HotSpotCustomLayoutV2Plan2': 32, 'CustomGraphics': 33, 'CloudConfigVersion': 34, 'CustomLayoutHelicopterV1Window': 35, 'CustomLayoutHelicopterV2Window': 36, 'CustomLayoutHelicopterV1Plan0': 37, 'CustomLayoutHelicopterV1Plan1': 38, 'CustomLayoutHelicopterV1Plan2': 39, 'CustomLayoutHelicopterV2Plan0': 40, 'CustomLayoutHelicopterV2Plan1': 41, 'CustomLayoutHelicopterV2Plan2': 42, 'ControlWindowPC': 43, 'ControlWindowController': 44}
    value_to_names = {1: 'BasicWindow', 2: 'GamePlayWindow', 3: 'ControlWindow', 5: 'CustomLayoutV1Window', 6: 'CustomLayoutV2Window', 7: 'CustomLayoutV1Plan0', 8: 'CustomLayoutV1Plan1', 9: 'CustomLayoutV1Plan2', 10: 'CustomLayoutV2Plan0', 11: 'CustomLayoutV2Plan1', 12: 'CustomLayoutV2Plan2', 13: 'CustomLayoutVehicleV1Window', 14: 'CustomLayoutVehicleV2Window', 15: 'CustomLayoutVehicleV1Plan0', 16: 'CustomLayoutVehicleV1Plan1', 17: 'CustomLayoutVehicleV1Plan2', 18: 'CustomLayoutVehicleV2Plan0', 19: 'CustomLayoutVehicleV2Plan1', 20: 'CustomLayoutVehicleV2Plan2', 21: 'SensitivityPlan1', 22: 'SensitivityPlan2', 23: 'SensitivityWindow', 24: 'AccountWindow', 25: 'HotSpotCustomLayoutV1Window', 26: 'HotSpotCustomLayoutV2Window', 27: 'HotSpotCustomLayoutV1Plan0', 28: 'HotSpotCustomLayoutV1Plan1', 29: 'HotSpotCustomLayoutV1Plan2', 30: 'HotSpotCustomLayoutV2Plan0', 31: 'HotSpotCustomLayoutV2Plan1', 32: 'HotSpotCustomLayoutV2Plan2', 33: 'CustomGraphics', 34: 'CloudConfigVersion', 35: 'CustomLayoutHelicopterV1Window', 36: 'CustomLayoutHelicopterV2Window', 37: 'CustomLayoutHelicopterV1Plan0', 38: 'CustomLayoutHelicopterV1Plan1', 39: 'CustomLayoutHelicopterV1Plan2', 40: 'CustomLayoutHelicopterV2Plan0', 41: 'CustomLayoutHelicopterV2Plan1', 42: 'CustomLayoutHelicopterV2Plan2', 43: 'ControlWindowPC', 44: 'ControlWindowController'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class enum:
    name_to_values = {}
    value_to_names = {}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...


# Functions
def GetCustomLayoutHelicopterV1PlanSettingTag(plan_idx): ...
def GetCustomLayoutV1PlanSettingTag(plan_idx): ...
def GetCustomLayoutV2PlanSettingTag(plan_idx): ...
def GetCustomLayoutVehicleV1PlanSettingTag(plan_idx): ...
def GetHotSpotCustomLayoutV1PlanSettingTag(plan_idx): ...
def GetHotSpotCustomLayoutV2PlanSettingTag(plan_idx): ...
def GetSensitivitySettingPlanTag(plan_idx): ...
def Property(name, default, flag=2): ...

