"""
Module: gshare.ispell_mgr
Dumped: 2025-12-16T22:16:58.646277
Generated by SDK Dumper
"""

# module: gshare.ispell_mgr

# Imports
import pickle
import gclient.framework.util.replay_util
import six2
import gclient.data.spell_data
import struct
import time
import gshare.time_util
import zlib

# Variables
BallisticEffectKeys = ['hit_dir', 'hit_dis', 'hit_pos', 'is_dual']
COMPONENT = 'Client'
CombatAvatarEvent = None
DamageResultKeys = ['hit_dir', 'weapon_id', 'hit_penetrate', 'damage', 'hit_back', 'is_ads', 'hit_part', 'immune_reason', 'is_burn']
HitEffectKeys = ['hit_effect_id', 'hit_material_type', 'hit_normal', 'hit_pos', 'hit_dir', 'target_id', 'weapon_id', 'no_effect', 'extra_effect_id']
KeysIndexCache = {}
SPELL_TICK_INTERVAL = 0.1
SoundResultKeys = ['material_type', 'pos']
SpellResultKeys = ['caster_pos', 'damage_result', 'is_hit', 'shoot_end_pos', 'hit_effect', 'ballistic_effect', 'bomb_result', 'spell_result', 'sound_result', 'shoot_start_pos', 'extra', 'spell_id', 'level', 'caster', 'cost_ammo', 'is_system_damage', 'cost_ammo_hand']
_reload_all = True
ballistic_effect_struct_keys = ('hit_dir', 'hit_pos')
hit_effect_struct_keys = ('hit_normal', 'hit_pos', 'hit_dir')
sound_result_struct_keys = ('pos',)

# Classes
class AttrType(enum):
    ANTI_RESTORE_HP_TIME = 7
    AmmoMaxStack = 22
    AssassinateEnergyUp = 47
    BackpackFreeSlot = 21
    BanSprint = 62
    BombBuffDuration = 18
    BombBuffRange = 17
    BombDamage = 16
    BombDamageRange = 15
    CannonDamage = 46
    CureUavCureSpeed = 42
    CureUavRangeUp = 65
    CureUavTimeUp = 66
    CureValueUp = 58
    EnergySkillChargeSpeed = 56
    EnergyValueUp = 26
    ForbidChangeWeapon = 55
    ForbidRestoreArmor = 60
    ForbidRestoreHP = 59
    FullScanTime = 43
    GasDamage = 41
    GasFiledDamage = 44
    GasRange = 40
    GasTime = 39
    Goggle = 5
    GunDamage = 23
    HeatResist = 6
    HelpOtherFinishHp = 20
    HelpOtherSpeed = 2
    Invincible = 61
    KillReward = 10
    LightRayDamage = 36
    LightRayRange = 37
    LightRayTime = 35
    MagicFieldEffectScaleX = 28
    MagicFieldEffectScaleY = 29
    MagicFieldEffectScaleZ = 30
    MaxArmor = 3
    MaxHp = 1
    MaxStack = 12
    MissileDamage = 32
    MissileStrikeCount = 31
    MoveDamageReduce = 54
    Ninja = 4
    ParanoiaDistance = 49
    ParanoiaRadius = 50
    ParanoiaTime = 51
    RecoverArmorSpeed = 19
    RecoverArmorTime = 24
    RecoverSpeed = 11
    SatelliteScanInterval = 38
    SatelliteScanRange = 34
    SatelliteScanTime = 33
    ShadowRange = 53
    ShadowTime = 52
    ShieldDuration = 27
    SkillChargeSpeed = 57
    SkillMaxCount = 64
    SkillRange = 45
    SkillRechargeTime = 13
    StorePrice = 14
    SupplyProb = 8
    TaskReward = 9
    UavRecoverArmorSpeed = 48
    UseCureItemSpeed = 63
    ZombieDamageDown = 67
    name_to_values = {'MaxHp': 1, 'HelpOtherSpeed': 2, 'MaxArmor': 3, 'Ninja': 4, 'Goggle': 5, 'HeatResist': 6, 'ANTI_RESTORE_HP_TIME': 7, 'SupplyProb': 8, 'TaskReward': 9, 'KillReward': 10, 'RecoverSpeed': 11, 'MaxStack': 12, 'SkillRechargeTime': 13, 'StorePrice': 14, 'BombDamageRange': 15, 'BombDamage': 16, 'BombBuffRange': 17, 'BombBuffDuration': 18, 'RecoverArmorSpeed': 19, 'HelpOtherFinishHp': 20, 'BackpackFreeSlot': 21, 'AmmoMaxStack': 22, 'GunDamage': 23, 'RecoverArmorTime': 24, 'EnergyValueUp': 26, 'ShieldDuration': 27, 'MagicFieldEffectScaleX': 28, 'MagicFieldEffectScaleY': 29, 'MagicFieldEffectScaleZ': 30, 'MissileStrikeCount': 31, 'MissileDamage': 32, 'SatelliteScanTime': 33, 'SatelliteScanRange': 34, 'LightRayTime': 35, 'LightRayDamage': 36, 'LightRayRange': 37, 'SatelliteScanInterval': 38, 'GasTime': 39, 'GasRange': 40, 'GasDamage': 41, 'CureUavCureSpeed': 42, 'FullScanTime': 43, 'GasFiledDamage': 44, 'SkillRange': 45, 'CannonDamage': 46, 'AssassinateEnergyUp': 47, 'UavRecoverArmorSpeed': 48, 'ParanoiaDistance': 49, 'ParanoiaRadius': 50, 'ParanoiaTime': 51, 'ShadowTime': 52, 'ShadowRange': 53, 'MoveDamageReduce': 54, 'ForbidChangeWeapon': 55, 'EnergySkillChargeSpeed': 56, 'SkillChargeSpeed': 57, 'CureValueUp': 58, 'ForbidRestoreHP': 59, 'ForbidRestoreArmor': 60, 'Invincible': 61, 'BanSprint': 62, 'UseCureItemSpeed': 63, 'SkillMaxCount': 64, 'CureUavRangeUp': 65, 'CureUavTimeUp': 66, 'ZombieDamageDown': 67}
    value_to_names = {1: 'MaxHp', 2: 'HelpOtherSpeed', 3: 'MaxArmor', 4: 'Ninja', 5: 'Goggle', 6: 'HeatResist', 7: 'ANTI_RESTORE_HP_TIME', 8: 'SupplyProb', 9: 'TaskReward', 10: 'KillReward', 11: 'RecoverSpeed', 12: 'MaxStack', 13: 'SkillRechargeTime', 14: 'StorePrice', 15: 'BombDamageRange', 16: 'BombDamage', 17: 'BombBuffRange', 18: 'BombBuffDuration', 19: 'RecoverArmorSpeed', 20: 'HelpOtherFinishHp', 21: 'BackpackFreeSlot', 22: 'AmmoMaxStack', 23: 'GunDamage', 24: 'RecoverArmorTime', 26: 'EnergyValueUp', 27: 'ShieldDuration', 28: 'MagicFieldEffectScaleX', 29: 'MagicFieldEffectScaleY', 30: 'MagicFieldEffectScaleZ', 31: 'MissileStrikeCount', 32: 'MissileDamage', 33: 'SatelliteScanTime', 34: 'SatelliteScanRange', 35: 'LightRayTime', 36: 'LightRayDamage', 37: 'LightRayRange', 38: 'SatelliteScanInterval', 39: 'GasTime', 40: 'GasRange', 41: 'GasDamage', 42: 'CureUavCureSpeed', 43: 'FullScanTime', 44: 'GasFiledDamage', 45: 'SkillRange', 46: 'CannonDamage', 47: 'AssassinateEnergyUp', 48: 'UavRecoverArmorSpeed', 49: 'ParanoiaDistance', 50: 'ParanoiaRadius', 51: 'ParanoiaTime', 52: 'ShadowTime', 53: 'ShadowRange', 54: 'MoveDamageReduce', 55: 'ForbidChangeWeapon', 56: 'EnergySkillChargeSpeed', 57: 'SkillChargeSpeed', 58: 'CureValueUp', 59: 'ForbidRestoreHP', 60: 'ForbidRestoreArmor', 61: 'Invincible', 62: 'BanSprint', 63: 'UseCureItemSpeed', 64: 'SkillMaxCount', 65: 'CureUavRangeUp', 66: 'CureUavTimeUp', 67: 'ZombieDamageDown'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class CustomListType(area_list):
    IS_CUSTOM_TYPE = True
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>


class CustomMapType(area_map):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class ISpell(CustomMapType):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    @property
    def charge_equip_id(self): ...

    @property
    def charge_limit(self): ...

    @property
    def charge_time(self): ...

    @property
    def cur_charge_speed(self): ...

    @property
    def cur_energy_progress(self): ...

    @property
    def cur_pct_progress(self): ...

    @property
    def hide_cd_when_charging(self): ...

    @property
    def in_energy_limit(self): ...

    @property
    def is_charge_finished(self): ...

    @property
    def is_charging(self): ...

    @property
    def is_energy_skill(self): ...

    @property
    def is_in_cd(self): ...

    @property
    def is_passive_skill(self): ...

    @property
    def proto(self): ...

    @property
    def show_decrease_charging_time(self): ...

    @property
    def show_increase_charging_time(self): ...

    @property
    def spell_cd(self): ...

    @property
    def spell_value(self): ...

    def ChangePctProgress(self, delta): ...

    def ClearProgress(self): ...

    def ClockProgress(self): ...

    def FillProgress(self): ...

    def StartCharge(self, charge_speed=None): ...

    def StopCharge(self): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class ISpellMgr(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.ispell_mgr.ISpell'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def AddSpell(self, spell_id, level=1, count=0): ...

    def CheckCanSpell(self, spell_id): ...

    def Clear(self): ...

    def OnSpellStop(self, spell_id, extra): ...

    def OnSpellStrike(self, spell_id, extra): ...

    def OnTick(self): ...

    def RemoveSpell(self, spell_id): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class OptionKey(enum):
    AirdropGauntlet = 'airdrop_gauntlet'
    AirdropStore = 'airdrop_store'
    AirdropSword = 'airdrop_sword'
    Airdrops = 'airdrop'
    AssistAim = 'assist_aim'
    AutoReborn = 'relive'
    BattleTime = 'time'
    CanBuyTacticalLevel = 'can_buy_tactical_level'
    CircleAirline = 'circle_airline'
    Coins = 'coins_range'
    DamageTeammate = 'damage_teammate'
    DisableBot = 'disable_bot'
    DisableSkill = 'disable_skill'
    DropCrystal = 'drop_crystal'
    EVOChargeSpeedRatio = 'evo_charge_speed_ratio'
    EnableEvo = 'enable_evo'
    EvaMonsterSpawn = 'eva_monster_spawn'
    ForbidAssistAim = 'forbid_assist_aim'
    HS_ONLY = 'hs_only'
    InfAmmo = 'infinite_ammo'
    InitTacticalLevel = 'tactical_level'
    JurenAirdropMore = 'juren_airdrop_more'
    JurenSKillNoCd = 'juren_skill_no_cd'
    LeaderMode = 'leader_mode'
    MaxArmor = 'maxarmor'
    MaxHp = 'max_hp'
    NextTime = 'race_begin'
    NoDeathTactical = 'disable_death_tactical_energy'
    OneShotKillChance = 'one_shot_kill_chance'
    PutInVehicle = 'vehicle'
    RaceDelayBegin = 'delay_begin'
    RaceManualStart = 'manual_start'
    RaceRounds = 'race_rounds'
    ReduceSkillCharge = 'reduce_skill_charge'
    RoundToWin = 'round_to_win'
    Rounds = 'round_range'
    SafeRegionDamage = 'safe_region_damage'
    SafeRegionSpeed = 'safe_region_speed'
    SameHero = 'same_hero'
    Score = 'score'
    TaskCount = 'task_count'
    TaskType = 'task_type'
    WeatherType = 'weather'
    ZombieBuyback = 'zombie_buyback'
    ZombieHp = 'zombie_hp'
    ZombieRebornItem = 'zombie_reborn_item'
    ZombieRevive = 'zombie_revive'
    name_to_values = {'MaxHp': 'max_hp', 'MaxArmor': 'maxarmor', 'DamageTeammate': 'damage_teammate', 'InfAmmo': 'infinite_ammo', 'DisableSkill': 'disable_skill', 'ForbidAssistAim': 'forbid_assist_aim', 'Rounds': 'round_range', 'LeaderMode': 'leader_mode', 'RoundToWin': 'round_to_win', 'Coins': 'coins_range', 'InitTacticalLevel': 'tactical_level', 'CanBuyTacticalLevel': 'can_buy_tactical_level', 'AutoReborn': 'relive', 'WeatherType': 'weather', 'PutInVehicle': 'vehicle', 'SafeRegionSpeed': 'safe_region_speed', 'SafeRegionDamage': 'safe_region_damage', 'Airdrops': 'airdrop', 'TaskCount': 'task_count', 'TaskType': 'task_type', 'AirdropStore': 'airdrop_store', 'AssistAim': 'assist_aim', 'DisableBot': 'disable_bot', 'NoDeathTactical': 'disable_death_tactical_energy', 'Score': 'score', 'BattleTime': 'time', 'AirdropSword': 'airdrop_sword', 'AirdropGauntlet': 'airdrop_gauntlet', 'ZombieRevive': 'zombie_revive', 'ZombieHp': 'zombie_hp', 'ZombieRebornItem': 'zombie_reborn_item', 'ZombieBuyback': 'zombie_buyback', 'HS_ONLY': 'hs_only', 'EnableEvo': 'enable_evo', 'EVOChargeSpeedRatio': 'evo_charge_speed_ratio', 'JurenSKillNoCd': 'juren_skill_no_cd', 'JurenAirdropMore': 'juren_airdrop_more', 'SameHero': 'same_hero', 'ReduceSkillCharge': 'reduce_skill_charge', 'CircleAirline': 'circle_airline', 'RaceManualStart': 'manual_start', 'RaceDelayBegin': 'delay_begin', 'RaceRounds': 'race_rounds', 'NextTime': 'race_begin', 'EvaMonsterSpawn': 'eva_monster_spawn', 'OneShotKillChance': 'one_shot_kill_chance', 'DropCrystal': 'drop_crystal'}
    value_to_names = {'max_hp': 'MaxHp', 'maxarmor': 'MaxArmor', 'damage_teammate': 'DamageTeammate', 'infinite_ammo': 'InfAmmo', 'disable_skill': 'DisableSkill', 'forbid_assist_aim': 'ForbidAssistAim', 'round_range': 'Rounds', 'leader_mode': 'LeaderMode', 'round_to_win': 'RoundToWin', 'coins_range': 'Coins', 'tactical_level': 'InitTacticalLevel', 'can_buy_tactical_level': 'CanBuyTacticalLevel', 'relive': 'AutoReborn', 'weather': 'WeatherType', 'vehicle': 'PutInVehicle', 'safe_region_speed': 'SafeRegionSpeed', 'safe_region_damage': 'SafeRegionDamage', 'airdrop': 'Airdrops', 'task_count': 'TaskCount', 'task_type': 'TaskType', 'airdrop_store': 'AirdropStore', 'assist_aim': 'AssistAim', 'disable_bot': 'DisableBot', 'disable_death_tactical_energy': 'NoDeathTactical', 'score': 'Score', 'time': 'BattleTime', 'airdrop_sword': 'AirdropSword', 'airdrop_gauntlet': 'AirdropGauntlet', 'zombie_revive': 'ZombieRevive', 'zombie_hp': 'ZombieHp', 'zombie_reborn_item': 'ZombieRebornItem', 'zombie_buyback': 'ZombieBuyback', 'hs_only': 'HS_ONLY', 'enable_evo': 'EnableEvo', 'evo_charge_speed_ratio': 'EVOChargeSpeedRatio', 'juren_skill_no_cd': 'JurenSKillNoCd', 'juren_airdrop_more': 'JurenAirdropMore', 'same_hero': 'SameHero', 'reduce_skill_charge': 'ReduceSkillCharge', 'circle_airline': 'CircleAirline', 'manual_start': 'RaceManualStart', 'delay_begin': 'RaceDelayBegin', 'race_rounds': 'RaceRounds', 'race_begin': 'NextTime', 'eva_monster_spawn': 'EvaMonsterSpawn', 'one_shot_kill_chance': 'OneShotKillChance', 'drop_crystal': 'DropCrystal'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class SpellChargeType(enum):
    NONE = 0
    TIME = 2
    VALUE = 1
    name_to_values = {'NONE': 0, 'VALUE': 1, 'TIME': 2}
    value_to_names = {0: 'NONE', 1: 'VALUE', 2: 'TIME'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class SpellResult:
    @property
    def proto(self): ...

    def CreateSimple(caster, spell_id, spell_level=1, direct_caster=None): ...

    def FillSimpleDamage(self, targetid, damage, weapon_id=None, **kwargs): ...

    def Pack(self): ...

    def SimpPack(self): ...

    def SimpUnpack(self, result_list): ...

    def Unpack(self, result): ...

    def _Dict2List(self, dict_data, keys): ...

    def _List2Dict(self, list_data, keys): ...


# Functions
def ExtraProperty(name, default): ...
def Property(name, default, flag=2): ...

