"""
Module: gshare.jarvis_storage
Dumped: 2025-12-16T22:16:58.683210
Generated by SDK Dumper
"""

# module: gshare.jarvis_storage

# Imports
import mobilerpc.HttpBase
import base64
import functools
import hashlib
import hmac
import json
import six2
import types
import urllib.parse
import uuid

# Variables
COMPONENT = 'Client'
Month = 2592000
PROJECT_ID = 'G83NAXX1ENA'
SECRET_KEY = '2e90e75069454955a33b949fbbe726f7'
UPLOAD_URI = '/jarvis/api/files'
_reload_all = True

# Classes
class DataType(enum):
    LOG = 1
    PICTURE = 2
    RECORD = 3
    name_to_values = {'LOG': 1, 'PICTURE': 2, 'RECORD': 3}
    value_to_names = {1: 'LOG', 2: 'PICTURE', 3: 'RECORD'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class JarvisStorage(Singleton):
    def Delete(self, fileid, callback=None, avatar=None): ...

    def Destroy(): ...

    def OnDestroy(self): ...

    def Upload(self, data, data_type, ttl=2592000, callback=None, avatar=None): ...

    def UploadRecord(self, data, expires=None, callback=None, player=None, retry=1): ...

    def UploadRecordPolicy(self, body, expires=None, callback=None, policy_extra=None, retry=1): ...

    def UploadScreen(self, body, expires=None, callback=None): ...

    def init(self): ...

    def instance(*args, **kwargs) -> ~T_SINGLETON_INST: ...

    def isInited(): ...

    def is_destroyed(): ...

class Singleton:
    def Destroy(): ...

    def OnDestroy(self): ...

    def init(self): ...

    def instance(*args, **kwargs) -> ~T_SINGLETON_INST: ...

    def isInited(): ...

    def is_destroyed(): ...

class enum:
    name_to_values = {}
    value_to_names = {}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...


# Functions
def GetHttpClient(name=None, max_clients=2, **kwargs): ...

