"""
Module: gshare.panpan_util
Dumped: 2025-12-16T22:16:58.690234
Generated by SDK Dumper
"""

# module: gshare.panpan_util

# Imports
import gclient.data.combat_item_data
import gshare.consts
import gclient.framework.util.events
import gshare.formula
import gclient.data.gun_skin_template_data
import gclient.data.lobby_item_data
import gclient.data.panpan_attr_data
import gclient.data.panpan_attr_lib_data
import gclient.data.panpan_attr_quality_weight_data
import gclient.data.panpan_attr_suit_data
import gclient.data.panpan_color_attr_data
import gclient.data.panpan_dyn_effect_attr_data
import gclient.data.panpan_lv_data
import gclient.data.panpan_position_attr_data
import gclient.data.panpan_privilege_data
import gclient.data.panpan_set_data
import gclient.data.panpan_sp_effect_attr_data
import gclient.data.panpan_wash_critical_data
import gclient.data.panpan_wash_guarantee_data
import random

# Variables
COMPONENT = 'Client'
OWN_CLIENT_PERSISTENT = 10

# Classes
class AppearAttrs(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'common.classutils.CustomIntListType'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class CustomIntListType(CustomListType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'int'>
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>


class CustomIntMapType(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'int'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class CustomMapType(area_map):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class LockAttrs(CustomIntListType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'int'>
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>

    def on_append(self): ...

    def on_pop(self, inx, old): ...

class PanpanAttrType(enum):
    color_attr = 1
    dyn_effect_attr = 3
    name_to_values = {'color_attr': 1, 'position_attr': 2, 'dyn_effect_attr': 3, 'sp_effect_attr': 4}
    position_attr = 2
    sp_effect_attr = 4
    value_to_names = {1: 'color_attr', 2: 'position_attr', 3: 'dyn_effect_attr', 4: 'sp_effect_attr'}

    def CopyAttr(from_panpan, to_panpan): ...

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class PanpanItem(CustomMapType):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    @property
    def color_attr(self): ...

    @property
    def cur_panpan_info(self): ...

    @property
    def cur_plan(self): ...

    @property
    def dyn_effect_attr(self): ...

    @property
    def panpan_attrs(self): ...

    @property
    def panpan_exp(self): ...

    @property
    def panpan_lv(self): ...

    @property
    def panpan_max_lv(self): ...

    @property
    def position_attr(self): ...

    @property
    def sp_effect_attr(self): ...

    @property
    def type_to_attrs(self): ...

    def GetPanpanPlan(self, plan_no): ...

    def IsUnlockPlan(self, plan_no): ...

    def PlanEnsure(self): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def on_setattr(self, key, old, new): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class PanpanMgr(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.panpan_util.PanpanItem'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def GetPanpanEnsure(self, guid): ...

    def GetUseTime(self, guid): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class PanpanPlan(CustomMapType):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    @property
    def panpan_attrs(self): ...

    @property
    def panpan_info(self): ...

    @property
    def type_to_attrs(self): ...

    def GetAttrValue(self, attr_type): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def on_setattr(self, key, old, new): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class PanpanPlans(CustomMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.panpan_util.PanpanPlan'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def on_setattr(self, key, old, new): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class PanpanPrivilegeState(enum):
    Finished = 1
    Init = 0
    Rewarded = 2
    name_to_values = {'Init': 0, 'Finished': 1, 'Rewarded': 2}
    value_to_names = {0: 'Init', 1: 'Finished', 2: 'Rewarded'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class PanpanPrivilegeType(enum):
    CombatBigEmote = 5
    CombatBillBoard = 2
    CombatCoin = 3
    CombatEntranceAnimation = 6
    GunSkip = 1
    IslandWorship = 4
    name_to_values = {'GunSkip': 1, 'CombatBillBoard': 2, 'CombatCoin': 3, 'IslandWorship': 4, 'CombatBigEmote': 5, 'CombatEntranceAnimation': 6}
    value_to_names = {1: 'GunSkip', 2: 'CombatBillBoard', 3: 'CombatCoin', 4: 'IslandWorship', 5: 'CombatBigEmote', 6: 'CombatEntranceAnimation'}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class PanpanPrivileges(CustomIntMapType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'int'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def on_setattr(self, key, old, new): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class PanpanWashInfo(CustomMapType):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    @property
    def panpan_attrs(self): ...

    @property
    def type_to_attrs(self): ...

    def CancelWashInfo(self): ...

    def GetAttrValue(self, attr_type): ...

    def InitWashInfo(self, guid, panpan): ...

    def IsEmpty(self): ...

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class enum:
    name_to_values = {}
    value_to_names = {}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...


# Functions
def GetAttrData(attr_type): ...
def GetPanPanAttrList(item_id, panpan_lv, attr_type): ...
def GetPanpanEquipId(lobby_item_id): ...
def GetPanpanGuaranteeAttrQuality(avatar, guid): ...
def GetPanpanLevelUpExp(quality, level): ...
def GetPanpanUnlockPlanCost(avatar, panpan_item_id, plan_no): ...
def GetPanpanWashCost(avatar, panpan_guid, lock_attrs): ...
def GetPrivilegeProto(item_id, privilege_type): ...
def GetUnlockLevel(attr_type): ...
def IsUnlockAttr(attr_type, panpan_lv): ...
def Property(name, default, flag=2): ...
def _GetPanpanWashCost(panpan_lv, quality, lock_attrs): ...

