"""
Module: gshare.popo_msg
Dumped: 2025-12-16T22:16:58.697670
Generated by SDK Dumper
"""

# module: gshare.popo_msg

# Imports
import MConfig
import functools
import json
import random
import six2
import six2.moves.urllib_parse
import traceback

# Variables
COMPONENT = 'Client'
client = <mobilerpc.BHttpClient.SimpleAsyncBHTTPClient object at 0x0000018EA3F0F550>

# Classes
class HttpRequest:
    pass

class SimpleAsyncHTTPClient:
    clients = set()

    def http_request(self, request, timeout, callback, protocols=3): ...


# Functions
def SendPopo(show_info, group_id=1414006): ...
def on_send_to_user(request, reply): ...
def send_to_user(popo, msg, font='宋体', italic='0', underline='0', color='000000', m_async='0', atuids=None): ...
def send_to_user_public(popo, msg): ...
def send_to_user_public_normal(popo, msg): ...

