"""
Module: gshare.pubsub
Dumped: 2025-12-16T22:16:58.705719
Generated by SDK Dumper
"""

# module: gshare.pubsub

# Imports
import inspect
import six2
import sys

# Variables
COMPONENT = 'Client'
ClassEvents = defaultdict(<class 'set'>, {})
OptCache = {<class 'gclient.util.login_util.LoginManager'>: {16: {'OnAccountCreated': <function LoginManager.OnAccountCreated at 0x0000018E9F7FCD60>}}, <class 'gshare.utils.Singleton'>: {}, <class 'gclient.framework.util.ui_display_statistics_mgr.UIDisplayStatisticsMgr'>: {639: {'OnShowWindow': <function UIDisplayStatisticsMgr.OnShowWindow at 0x0000018E9F7DD080>}}, <class 'gclient.framework.sound.sound_manager.SoundManager'>: {649: {'OnAudioSessionRouteChange': <function SoundManager.OnAudioSessionRouteChange at 0x0000018E9F697F60>}, 594: {'OnRefreshSoundDlcStatus': <function SoundManager.OnRefreshSoundDlcStatus at 0x0000018E9F728040>}}, <class 'gclient.framework.ui.ui_stage.UIStage'>: {}, <class 'gclient.ui.uilogin.login_uistage.LoginUIStage'>: {5: {'OnNetworkStatusChanged': <function LoginUIStage.OnNetworkStatusChanged at 0x0000018EA5367C40>}}, <class 'gclient.ui.uilogin.login_window.LoginWindow'>: {746: {'OnGetIpRegion': <function LoginWindow.OnGetIpRegion at 0x0000018EA5365760>}, 591: {'RefreshPanelLogin': <function LoginWindow.RefreshPanelLogin at 0x0000018EA53658A0>}, 10: {'ShowLoginChannelEntry': <function LoginWindow.ShowLoginChannelEntry at 0x0000018EA53659E0>}, 11: {'OnLoginStateUpdate': <function LoginWindow.OnLoginStateUpdate at 0x0000018EA5366020>}, 12: {'OnLoginBindHostReady': <function LoginWindow.OnLoginBindHostReady at 0x0000018EA53660C0>}, 14: {'OnFetchServerlist': <function LoginWindow.OnFetchServerlist at 0x0000018EA5366200>}, 4: {'OnScreenSizeChanged': <function LoginWindow.OnScreenSizeChanged at 0x0000018EA5367420>}, 18: {'OnBeRelayed': <function LoginWindow.OnBeRelayed at 0x0000018EA5367600>}}, <class 'gclient.ui.common.reconnect_window.ReconnectingWindowBase'>: {}, <class 'gclient.ui.common.reconnect_window.LoginLoadingWindow'>: {11: {'OnLoginStateChange': <function LoginLoadingWindow.OnLoginStateChange at 0x0000018E9F7DE520>}, 16: {'OnAvatarCreated': <function LoginLoadingWindow.OnAvatarCreated at 0x0000018E9F7DE5C0>}}}
RecursiveWhiteList = {1, 2, 3}

# Classes
class LogManager:
    asyncwrite = False
    created_modules = {'ClientEnv', 'ServerUtil', 'Preload', 'bhttp_client.BHttpClient', 'Entity', 'Avatar', 'AsioServerProxy', 'PlayerAvatar', 'Model', 'BiologicalRay', 'Doll', 'RpcIndexer', 'Space', 'PlayerEntity', 'asynctimer', 'GateClient', 'mobilerpc.SimpleAsyncBHTTPClient', 'ClientEntity', 'ReplayDummy', 'server.EntityManager', 'BigHeadCalculationDoll', 'Pubsub', 'ClientAreaEntity', 'Account', 'CombatItemEntity', 'SwordSpirit', 'ModelCache', 'SpectatorDecorator', 'AvatarEntity', 'RPGMissile', 'Formula', 'ClientSpace', 'DollLike', 'CalculationDoll', 'server.EntityFactory'}
    custom_handler = None
    log_handle = 'stream'
    log_level = 10
    log_tag = ''
    run_tag = ''
    sa_log_tag = ''
    sys_logger = None

    def _create_handler(logger): ...

    def get_logger(moduleName): ...

    def get_sa_logger(): ...

    def run_message(message): ...

    def set_asyncwrite(asyncwrite): ...

    def set_custom_handler(handler): ...

    def set_log_handle(handle): ...

    def set_log_level(lv): ...

    def set_log_tag(log_tag): ...

    def set_run_tag(run_tag): ...

    def set_sa_log_tag(tag): ...

class Pubsub:
    _instance = <gshare.pubsub.Pubsub object at 0x0000018EFF561CD0>

    def CancelSubscribeEvent(self, instance): ...

    def OnTick(self): ...

    def Publish(self, event_id, *args, **kwargs): ...

    def SubscribeEvent(self, instance): ...

    def doCancelSubscribeEvent(self, instance): ...

    def doSubscribeEvent(self, instance): ...

class SingletonMeta(type):
    mro = <method 'mro' of 'type' objects>


class Swallower:
    pass

class defaultdict(dict):
    clear = <method 'clear' of 'dict' objects>
    copy = <method 'copy' of 'collections.defaultdict' objects>
    default_factory = <member 'default_factory' of 'collections.defaultdict' objects>
    fromkeys = <built-in method fromkeys of type object at 0x00007FF75EB17CC0>
    get = <method 'get' of 'dict' objects>
    items = <method 'items' of 'dict' objects>
    keys = <method 'keys' of 'dict' objects>
    pop = <method 'pop' of 'dict' objects>
    popitem = <method 'popitem' of 'dict' objects>
    setdefault = <method 'setdefault' of 'dict' objects>
    update = <method 'update' of 'dict' objects>
    values = <method 'values' of 'dict' objects>



# Functions
def Broadcast(event_id, *args, **kwargs): ...
def GetClsListenersDP(cls, depth=0): ...
def GetPublishEvent(cls): ...
def Publish(event_id, *args, **kwargs): ...
def ReloadClsListeners(cls): ...

