"""
Module: gshare.pyany
Dumped: 2025-12-16T22:16:58.706761
Generated by SDK Dumper
"""

# module: gshare.pyany

# Variables
COMPONENT = 'Client'

# Classes
class PyAny(dict):
    clear = <method 'clear' of 'dict' objects>
    copy = <method 'copy' of 'dict' objects>
    fromkeys = <built-in method fromkeys of type object at 0x0000018E9E9209C0>
    get = <method 'get' of 'dict' objects>
    items = <method 'items' of 'dict' objects>
    keys = <method 'keys' of 'dict' objects>
    pop = <method 'pop' of 'dict' objects>
    popitem = <method 'popitem' of 'dict' objects>
    setdefault = <method 'setdefault' of 'dict' objects>
    update = <method 'update' of 'dict' objects>
    values = <method 'values' of 'dict' objects>



