"""
Module: gshare.returning_player_util
Dumped: 2025-12-16T22:16:58.713094
Generated by SDK Dumper
"""

# module: gshare.returning_player_util

# Imports
import gclient.data.game_const_data

# Variables
COMPONENT = 'Client'
RETURNING_LOGOUT_TIME = 1296000
RETURNING_MIN_LEVEL = 4
RETURNING_RECORDS_MAX = 3
RETURNING_TIME = 1296000
SECOND_RETURNING_MIN_TIME = 2592000

