"""
Module: gshare.time_hook
Dumped: 2025-12-16T22:16:58.721922
Generated by SDK Dumper
"""

# module: gshare.time_hook

# Imports
import datetime
import time

# Variables
_OFFSET = 0.0
_datetime = None
_time_gmtime = None
_time_localtime = None
_time_strftime = None
_time_time = None
logger = <Logger ServerUtil (DEBUG)>

# Classes
class Crontab:
    TRIGGER_OFFSET = 5.1

    def _checkCrontabs(self): ...

    def _resetMinuteTimer(self): ...

    def init(self): ...

    def register(self, rule, callback): ...

    def resetTimer(self): ...

    def setup_frame_skipping_callback(self, callback): ...

    def stop(self): ...

    def unregister(self, rowid): ...

class LogManager:
    asyncwrite = False
    created_modules = {'ClientEnv', 'ServerUtil', 'Preload', 'bhttp_client.BHttpClient', 'Entity', 'Avatar', 'AsioServerProxy', 'PlayerAvatar', 'Model', 'BiologicalRay', 'Doll', 'RpcIndexer', 'Space', 'PlayerEntity', 'asynctimer', 'GateClient', 'mobilerpc.SimpleAsyncBHTTPClient', 'ClientEntity', 'ReplayDummy', 'server.EntityManager', 'BigHeadCalculationDoll', 'Pubsub', 'ClientAreaEntity', 'Account', 'CombatItemEntity', 'SwordSpirit', 'ModelCache', 'SpectatorDecorator', 'AvatarEntity', 'RPGMissile', 'Formula', 'ClientSpace', 'DollLike', 'CalculationDoll', 'server.EntityFactory'}
    custom_handler = None
    log_handle = 'stream'
    log_level = 10
    log_tag = ''
    run_tag = ''
    sa_log_tag = ''
    sys_logger = None

    def _create_handler(logger): ...

    def get_logger(moduleName): ...

    def get_sa_logger(): ...

    def run_message(message): ...

    def set_asyncwrite(asyncwrite): ...

    def set_custom_handler(handler): ...

    def set_log_handle(handle): ...

    def set_log_level(lv): ...

    def set_log_tag(log_tag): ...

    def set_run_tag(run_tag): ...

    def set_sa_log_tag(tag): ...

class datetime2(datetime):
    astimezone = <method 'astimezone' of 'datetime.datetime' objects>
    combine = <built-in method combine of type object at 0x0000018E9F13A900>
    ctime = <method 'ctime' of 'datetime.datetime' objects>
    date = <method 'date' of 'datetime.datetime' objects>
    day = <attribute 'day' of 'datetime.date' objects>
    dst = <method 'dst' of 'datetime.datetime' objects>
    fold = <attribute 'fold' of 'datetime.datetime' objects>
    fromisocalendar = <built-in method fromisocalendar of type object at 0x0000018E9F13A900>
    fromisoformat = <built-in method fromisoformat of type object at 0x0000018E9F13A900>
    fromordinal = <built-in method fromordinal of type object at 0x0000018E9F13A900>
    fromtimestamp = <built-in method fromtimestamp of type object at 0x0000018E9F13A900>
    hour = <attribute 'hour' of 'datetime.datetime' objects>
    isocalendar = <method 'isocalendar' of 'datetime.date' objects>
    isoformat = <method 'isoformat' of 'datetime.datetime' objects>
    isoweekday = <method 'isoweekday' of 'datetime.date' objects>
    max = datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)
    microsecond = <attribute 'microsecond' of 'datetime.datetime' objects>
    min = datetime.datetime(1, 1, 1, 0, 0)
    minute = <attribute 'minute' of 'datetime.datetime' objects>
    month = <attribute 'month' of 'datetime.date' objects>
    replace = <method 'replace' of 'datetime.datetime' objects>
    resolution = datetime.timedelta(microseconds=1)
    second = <attribute 'second' of 'datetime.datetime' objects>
    strftime = <method 'strftime' of 'datetime.date' objects>
    strptime = <built-in method strptime of type object at 0x0000018E9F13A900>
    time = <method 'time' of 'datetime.datetime' objects>
    timestamp = <method 'timestamp' of 'datetime.datetime' objects>
    timetuple = <method 'timetuple' of 'datetime.datetime' objects>
    timetz = <method 'timetz' of 'datetime.datetime' objects>
    toordinal = <method 'toordinal' of 'datetime.date' objects>
    tzinfo = <attribute 'tzinfo' of 'datetime.datetime' objects>
    tzname = <method 'tzname' of 'datetime.datetime' objects>
    utcfromtimestamp = <built-in method utcfromtimestamp of type object at 0x0000018E9F13A900>
    utcnow = <built-in method utcnow of type object at 0x0000018E9F13A900>
    utcoffset = <method 'utcoffset' of 'datetime.datetime' objects>
    utctimetuple = <method 'utctimetuple' of 'datetime.datetime' objects>
    weekday = <method 'weekday' of 'datetime.date' objects>
    year = <attribute 'year' of 'datetime.date' objects>

    def now(*args): ...

    def today(*args): ...


# Functions
def DoHookTime(offset): ...
def HookTime(offset): ...
def SetTime(year, mon, mday, hour=0, min=0, sec=0, ms=0): ...
def _gmtime(sec=0): ...
def _localtime(sec=None): ...
def _strftime(formats, tp=None): ...
def _time(): ...

