"""
Module: gshare.utils
Dumped: 2025-12-16T22:16:58.754128
Generated by SDK Dumper
"""

# module: gshare.utils

# Imports
import base64
import functools
import inspect
import json
import operator
import six2
import sys
import time
import weakref
import zlib

# Variables
COMPONENT = 'Client'
T_SINGLETON_INST = ~T_SINGLETON_INST
Type = typing.Type
get_ident = <built-in function get_ident>

# Classes
class BatchObj:
    _objs = <member '_objs' of 'BatchObj' objects>


class BatchObjIter(BatchObj):
    _len = <member '_len' of 'BatchObjIter' objects>
    _objs = <member '_objs' of 'BatchObjIter' objects>


class BitList(CustomIntListType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'int'>
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>

    def CheckBit(self, n): ...

    def CleanBits(self): ...

    def ClearBit(self, n): ...

    def GetBits(self): ...

    def SetBit(self, n): ...

    def on_update(self, index, old): ...

class BitListMap(CustomMapType):
    INTERVAL = 1000
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'gshare.utils.BitList'>
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def CheckBit(self, n): ...

    def ClearBit(self, n): ...

    def GetBits(self): ...

    def SetBit(self, n): ...

    def _initProperty(self, data): ...

    def _on_update_bit(self, i, bit): ...

    def items(self): ...

    def keys(self): ...

    def on_init(self, parent): ...

    def on_setattr(self, key, old, new): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class BitListOp:
    INT_BIT_LEN = 63

    def CheckBit(value, n): ...

    def CleanBits(value): ...

    def ClearBit(value, n): ...

    def GetBits(value): ...

    def GetIdx(n): ...

    def SetBit(value, n): ...

class Cache(OrderedDict):
    _OrderedDict__marker = <object object at 0x0000018EF52F4B90>
    get = <method 'get' of 'dict' objects>

    def _OrderedDict__update(self, other=(), /, **kwds): ...

    def clean(self): ...

    def cleantimeout(self, now, count=1000): ...

    def clear(self): ...

    def copy(self): ...

    def fromkeys(iterable, value=None): ...

    def front_item(self): ...

    def front_key(self): ...

    def front_value(self): ...

    def getdatas(self): ...

    def invalid(self, key): ...

    def items(self): ...

    def iteritems(self): yield ...

    def iterkeys(self): ...

    def itervalues(self): yield ...

    def keys(self): ...

    def move_to_end(self, key, last=True): ...

    def pop(self, key, default=<object object at 0x0000018EF52F4B90>): ...

    def popitem(self, last=True): ...

    def select(self, key, timeout=None): ...

    def setdefault(self, key, default=None): ...

    def update(self, key, value, timeout=0): ...

    def update_time(self, key): ...

    def values(self): ...

class CustomIntListType(CustomListType):
    IS_CUSTOM_TYPE = True
    VALUE_TYPE = <class 'int'>
    append = <method 'append' of 'area_list' objects>
    assign = <method 'assign' of 'area_list' objects>
    clear = <method 'clear' of 'area_list' objects>
    copy = <method 'copy' of 'area_list' objects>
    delete = <method 'delete' of 'area_list' objects>
    extend = <method 'extend' of 'area_list' objects>
    get = <method 'get' of 'area_list' objects>
    get_owner = <method 'get_owner' of 'area_list' objects>
    get_parent = <method 'get_parent' of 'area_list' objects>
    insert = <method 'insert' of 'area_list' objects>
    list = <method 'list' of 'area_list' objects>
    pop = <method 'pop' of 'area_list' objects>
    size = <method 'size' of 'area_list' objects>
    slice = <method 'slice' of 'area_list' objects>
    sorted = <method 'sorted' of 'area_list' objects>
    update = <method 'update' of 'area_list' objects>


class CustomMapType(area_map):
    IS_CUSTOM_TYPE = True
    clear = <method 'clear' of 'area_map' objects>
    copy = <method 'copy' of 'area_map' objects>
    dict = <method 'dict' of 'area_map' objects>
    dsize = <method 'dsize' of 'area_map' objects>
    get = <method 'get' of 'area_map' objects>
    get_owner = <method 'get_owner' of 'area_map' objects>
    get_parent = <method 'get_parent' of 'area_map' objects>
    iteritems = <method 'iteritems' of 'area_map' objects>
    iterkeys = <method 'iterkeys' of 'area_map' objects>
    itervalues = <method 'itervalues' of 'area_map' objects>
    normal_iteritems = <method 'normal_iteritems' of 'area_map' objects>
    normal_iterkeys = <method 'normal_iterkeys' of 'area_map' objects>
    normal_itervalues = <method 'normal_itervalues' of 'area_map' objects>
    pop = <method 'pop' of 'area_map' objects>
    props_all = <method 'props_all' of 'area_map' objects>
    size = <method 'size' of 'area_map' objects>
    total_size = <method 'total_size' of 'area_map' objects>
    update = <method 'update' of 'area_map' objects>
    weak_dict = <method 'weak_dict' of 'area_map' objects>

    def _initProperty(self, data): ...

    def items(self): ...

    def keys(self): ...

    def setdefault(self, key, default): ...

    def show_memory_status(self): ...

    def update2(self, data): ...

    def values(self): ...

class Dispatcher:
    record = <member 'record' of 'Dispatcher' objects>

    def dispatch(self, tag, *args, **kwargs): ...

    def register(self, tag, callback): ...

    def release(self): ...

    def unregister(self, tag, callback): ...

    def unregister_tag(self, tag): ...

class EnumMetaclass(type):
    mro = <method 'mro' of 'type' objects>


class Functor:
    pass

class List2D(list):
    clear = <method 'clear' of 'list' objects>
    copy = <method 'copy' of 'list' objects>
    count = <method 'count' of 'list' objects>
    index = <method 'index' of 'list' objects>
    insert = <method 'insert' of 'list' objects>
    pop = <method 'pop' of 'list' objects>
    remove = <method 'remove' of 'list' objects>
    reverse = <method 'reverse' of 'list' objects>
    sort = <method 'sort' of 'list' objects>

    def Create(iterable, line_size): ...

    def CreateByList(list_or_tuple, line_size): ...

    def IterByList(list_or_tuple, line_size): yield ...

    def append(self, p_object): ...

    def extend(self, iterable): ...

class LogInvoke:
    pass

class LruCache(OrderedDict):
    _OrderedDict__marker = <object object at 0x0000018EF52F4B90>
    get = <method 'get' of 'dict' objects>

    def _OrderedDict__update(self, other=(), /, **kwds): ...

    def clean(self): ...

    def clear(self): ...

    def copy(self): ...

    def fromkeys(iterable, value=None): ...

    def front_item(self): ...

    def front_key(self): ...

    def front_value(self): ...

    def invalid(self, key): ...

    def items(self): ...

    def iteritems(self): yield ...

    def iterkeys(self): ...

    def itervalues(self): yield ...

    def keys(self): ...

    def move_to_end(self, key, last=True): ...

    def pop(self, key, default=<object object at 0x0000018EF52F4B90>): ...

    def popitem(self, last=True): ...

    def select(self, key): ...

    def setdefault(self, key, default=None): ...

    def update(self, key, value): ...

    def values(self): ...

class MutableMapping(Mapping):
    _MutableMapping__marker = <object object at 0x0000018EF52F41C0>
    _abc_impl = <_abc._abc_data object at 0x0000018EF545F240>

    def clear(self): ...

    def get(self, key, default=None): ...

    def items(self): ...

    def keys(self): ...

    def pop(self, key, default=<object object at 0x0000018EF52F41C0>): ...

    def popitem(self): ...

    def setdefault(self, key, default=None): ...

    def update(self, other=(), /, **kwds): ...

    def values(self): ...

class NonexistentSwallower(Swallower):
    pass

class OrderedDict(dict):
    _OrderedDict__marker = <object object at 0x0000018EF52F4B90>
    get = <method 'get' of 'dict' objects>

    def _OrderedDict__update(self, other=(), /, **kwds): ...

    def clear(self): ...

    def copy(self): ...

    def fromkeys(iterable, value=None): ...

    def front_item(self): ...

    def front_key(self): ...

    def front_value(self): ...

    def items(self): ...

    def iteritems(self): yield ...

    def iterkeys(self): ...

    def itervalues(self): yield ...

    def keys(self): ...

    def move_to_end(self, key, last=True): ...

    def pop(self, key, default=<object object at 0x0000018EF52F4B90>): ...

    def popitem(self, last=True): ...

    def setdefault(self, key, default=None): ...

    def update(self, other=(), /, **kwds): ...

    def values(self): ...

class Singleton:
    def Destroy(): ...

    def OnDestroy(self): ...

    def init(self): ...

    def instance(*args, **kwargs) -> ~T_SINGLETON_INST: ...

    def isInited(): ...

    def is_destroyed(): ...

class SingletonMeta(type):
    mro = <method 'mro' of 'type' objects>


class SlotsEnum:
    pass

class SlotsEnumMetaClass(_SlotsEnumMetaClassBase):
    mro = <method 'mro' of 'type' objects>

    def from_string(cls, name): ...

    def to_string(cls, idx): ...

class SlotsEnumStr:
    pass

class SlotsEnumStrMetaClass(_SlotsEnumMetaClassBase):
    mro = <method 'mro' of 'type' objects>

    def to_idx(cls, name): ...

class SmartSingleton(Singleton):
    REFS = set()

    def Destroy(): ...

    def GetInstance(user, *args, **kwargs) -> ~T_SINGLETON_INST: ...

    def OnDestroy(self): ...

    def ReleaseInstance(user): ...

    def init(self): ...

    def instance(*args, **kwargs) -> ~T_SINGLETON_INST: ...

    def isInited(): ...

    def is_destroyed(): ...

class Swallower:
    pass

class TypeVar(_Final, _Immutable, _BoundVarianceMixin, _PickleUsingNameMixin):
    pass

class _Link:
    key = <member 'key' of '_Link' objects>
    next = <member 'next' of '_Link' objects>
    prev = <member 'prev' of '_Link' objects>


class _SlotsEnumMetaClassBase(type):
    mro = <method 'mro' of 'type' objects>


class defaultdict(dict):
    clear = <method 'clear' of 'dict' objects>
    copy = <method 'copy' of 'collections.defaultdict' objects>
    default_factory = <member 'default_factory' of 'collections.defaultdict' objects>
    fromkeys = <built-in method fromkeys of type object at 0x00007FF75EB17CC0>
    get = <method 'get' of 'dict' objects>
    items = <method 'items' of 'dict' objects>
    keys = <method 'keys' of 'dict' objects>
    pop = <method 'pop' of 'dict' objects>
    popitem = <method 'popitem' of 'dict' objects>
    setdefault = <method 'setdefault' of 'dict' objects>
    update = <method 'update' of 'dict' objects>
    values = <method 'values' of 'dict' objects>


class enum:
    name_to_values = {}
    value_to_names = {}

    def add_string(name, value): ...

    def from_string(name): ...

    def to_string(value): ...

    def to_values(): ...

    def values(): ...

class islice:
    pass


# Functions
def Account2Sdkuid(account): ...
def CompressedProperty(name, default): ...
def EnsureSafeStr(s): ...
def GSharePrompt(proto_id, extra_data=None, extra_info=None): ...
def JsonUTF8Loads(d): ...
def NormalDecrypt(key, cur_input): ...
def NormalEncrypt(key, cur_input): ...
def UTF8(string): ...
def UnicodeToUTF8(d): ...
def clamp(val, low, high): ...
def decryptString(data): ...
def encryptString(data): ...
def recursive_repr(fillvalue='...'): ...

