"""
Module: gshare.variance_mgr
Dumped: 2025-12-16T22:16:58.756082
Generated by SDK Dumper
"""

# module: gshare.variance_mgr

# Classes
class VarianceMgr:
    def AddData(self, data): ...

    def CalculateVariance(self, data): ...

    def GetMaxAndClear(self): ...


